// @generated by Cratis. Source: TestApps.Features.AuthenticationQueries.AuthenticationQueryItem. Time: 2026-07-19T23:32:51.1097230Z. Hash: C52CE17A7B1534A903598E9E65EE2D23B737D9983EA8C1285AF783B39C866F6F
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, QueryValidator } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { AuthenticationQueryItem } from './AuthenticationQueryItem';


export class AnonymousValidator extends QueryValidator<object> {
    constructor() {
        super();
    }
}

export class Anonymous extends ObservableQueryFor<AuthenticationQueryItem> {
    readonly route: string = '/api/features/authentication-queries/anonymous';
    readonly queryName: string = 'TestApps.Features.AuthenticationQueries.AuthenticationQueryItem.Anonymous';
    readonly validation: QueryValidator = new AnonymousValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: AuthenticationQueryItem = {} as any;

    constructor() {
        super(AuthenticationQueryItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useObservableQuery<AuthenticationQueryItem, Anonymous>(Anonymous);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useSuspenseObservableQuery<AuthenticationQueryItem, Anonymous>(Anonymous);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Anonymous, AuthenticationQueryItem> {
        return new ObservableQueryWhen<Anonymous, AuthenticationQueryItem>(Anonymous, condition);
    }
}
