// @generated by Cratis. Source: TestApps.Features.AuthenticationQueries.AuthenticationQueryItem. Time: 2026-03-27T14:51:06.3181380Z. Hash: 22BC2558859AFDCFD0998E30E098E9CFF2684C5DC20FC6FEA7EB52DBB6AB83EE
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { AuthenticationQueryItem } from './AuthenticationQueryItem';


export class Anonymous extends ObservableQueryFor<AuthenticationQueryItem> {
    readonly route: string = '/api/features/authentication-queries/anonymous';
    readonly queryName: string = 'TestApps.Features.AuthenticationQueries.AuthenticationQueryItem.Anonymous';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: AuthenticationQueryItem = {} as any;

    constructor() {
        super(AuthenticationQueryItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useObservableQuery<AuthenticationQueryItem, Anonymous>(Anonymous);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useSuspenseObservableQuery<AuthenticationQueryItem, Anonymous>(Anonymous);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Anonymous, AuthenticationQueryItem> {
        return new ObservableQueryWhen<Anonymous, AuthenticationQueryItem>(Anonymous, condition);
    }
}
