// @generated by Cratis. Source: TestApps.Features.AuthenticationQueries.AuthenticationQueryItem. Time: 2026-07-20T10:41:43.4511480Z. Hash: BFB2BB1DEBEFFDE006AEDCCCC4FDC4999B7B586EF0F8567ED48BCE6BBC3A4F7D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { AuthenticationQueryItem } from './AuthenticationQueryItem';



export class Authenticated extends ObservableQueryFor<AuthenticationQueryItem> {
    readonly route: string = '/api/features/authentication-queries/authenticated';
    readonly queryName: string = 'TestApps.Features.AuthenticationQueries.AuthenticationQueryItem.Authenticated';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: AuthenticationQueryItem = {} as any;

    constructor() {
        super(AuthenticationQueryItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useObservableQuery<AuthenticationQueryItem, Authenticated>(Authenticated);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useSuspenseObservableQuery<AuthenticationQueryItem, Authenticated>(Authenticated);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Authenticated, AuthenticationQueryItem> {
        return new ObservableQueryWhen<Authenticated, AuthenticationQueryItem>(Authenticated, condition);
    }
}
