// @generated by Cratis. Source: TestApps.Features.AuthenticationQueries.AuthenticationQueryItem. Time: 2026-03-27T15:13:09.0538610Z. Hash: 5B042AD7DB6B26FC83F937303DB743363417A58159BCBC26D7A7B3AEFD1B77F6
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

export class AuthenticationQueryItem {
    @field(String)
    message!: string;
}
