<?xml version="1.0" encoding="UTF-8" ?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Cratis.Arc.Testing.Specs</AssemblyName>
        <RootNamespace>Cratis.Arc.Testing</RootNamespace>
        <IsTestProject>true</IsTestProject>
        <IsPackable>false</IsPackable>
        <TargetFrameworks>net10.0</TargetFrameworks>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Testing/Testing.csproj" />
    </ItemGroup>
</Project>
