// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Cratis.Arc.Generators;

/// <summary>
/// Generates the members the validation traversal walks for the model types reachable from model-bound commands and
/// query arguments, registered with typed getters so the traversal does not reflect over them.
/// </summary>
[Generator]
public class ModelGraphWalkerGenerator : IIncrementalGenerator
{
    const string CommandAttribute = "Cratis.Arc.Commands.ModelBound.CommandAttribute";
    const string ReadModelAttribute = "Cratis.Arc.Queries.ModelBound.ReadModelAttribute";
    const string Walkers = "Cratis.Arc.Validation.ModelGraphWalkers";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commands = context.SyntaxProvider.ForAttributeWithMetadataName(
            CommandAttribute,
            static (node, _) => node is TypeDeclarationSyntax,
            static (syntax, _) => syntax.TargetSymbol is INamedTypeSymbol command && syntax.SemanticModel.Compilation.GetTypeByMetadataName(Walkers) is not null
                ? new EquatableArray<ModelGraphWalker>(ModelGraphWalkerTypes.For([command], syntax.SemanticModel.Compilation))
                : new EquatableArray<ModelGraphWalker>([]))
            .Collect();

        var queries = context.SyntaxProvider.ForAttributeWithMetadataName(
            ReadModelAttribute,
            static (node, _) => node is TypeDeclarationSyntax,
            static (syntax, _) => syntax.TargetSymbol is INamedTypeSymbol readModel && syntax.SemanticModel.Compilation.GetTypeByMetadataName(Walkers) is not null
                ? new EquatableArray<ModelGraphWalker>(ModelGraphWalkerTypes.For(QueryArgumentTypes(readModel, syntax.SemanticModel.Compilation), syntax.SemanticModel.Compilation))
                : new EquatableArray<ModelGraphWalker>([]))
            .Collect();

        context.RegisterSourceOutput(commands.Combine(queries), static (output, roots) =>
        {
            var walkers = roots.Left.Concat(roots.Right).SelectMany(walker => walker)
                .GroupBy(walker => walker.Type, StringComparer.Ordinal)
                .Select(group => group.First())
                .OrderBy(walker => walker.Type, StringComparer.Ordinal)
                .ToArray();
            if (walkers.Length == 0)
            {
                return;
            }

            var source = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace Cratis.Arc.Validation.Generated;\ninternal static class ModelGraphWalkerRegistration\n{\n    [global::System.Runtime.CompilerServices.ModuleInitializer]\n    internal static void Initialize()\n    {\n");
            foreach (var walker in walkers)
            {
                source.AppendLine(walker.Registration);
            }

            source.AppendLine("    }\n}");
            output.AddSource("ModelGraphWalkers.g.cs", source.ToString());
        });
    }

    /// <summary>
    /// Gets the types a read model's queries are validated through: the parameters of its query methods, and the
    /// types that can model a query's argument set by the convention the query pipeline resolves them with.
    /// </summary>
    /// <remarks>
    /// Which parameters are dependencies rather than arguments is only known from the service registrations at
    /// runtime, so every parameter is a root; a dependency only adds walkers that are never used.
    /// </remarks>
    /// <param name="readModel">The read model type.</param>
    /// <param name="compilation">The compilation the generated code is emitted into.</param>
    /// <returns>The types to start from.</returns>
    static IEnumerable<ITypeSymbol> QueryArgumentTypes(INamedTypeSymbol readModel, Compilation compilation)
    {
        var queries = readModel.GetMembers().OfType<IMethodSymbol>()
            .Where(method => method.MethodKind == MethodKind.Ordinary && method.IsStatic && method.TypeParameters.Length == 0 &&
                method.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal &&
                !method.GetAttributes().Any(attribute => string.Equals(attribute.AttributeClass?.ToDisplayString(), "System.Runtime.CompilerServices.CompilerGeneratedAttribute", StringComparison.Ordinal)) &&
                QueryMetadataGenerator.IsValidQueryMethod(method, readModel))
            .ToArray();

        // Mirrors QueryArgumentsModelConvention.CandidateNamesFor, which the generator cannot compile in.
        var candidates = new HashSet<string>(
            queries.SelectMany(query => new[] { $"{readModel.Name}{query.Name}Parameters", $"{query.Name}Parameters" }),
            StringComparer.OrdinalIgnoreCase);
        var models = compilation.GetSymbolsWithName(candidates.Contains, SymbolFilter.Type).OfType<ITypeSymbol>();

        return queries.SelectMany(query => query.Parameters).Select(parameter => parameter.Type).Concat(models);
    }
}
