// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Cratis.Arc.Generators;

/// <summary>
/// Incremental source generator that lets an executable run the module initializers of its project references without
/// resolving them at runtime.
/// </summary>
/// <remarks>
/// <para>
/// Generated metadata - query metadata, command operation invokers and Fundamentals type discovery providers - is
/// registered from a <c>[ModuleInitializer]</c> in the assembly it describes, and the runtime runs a module initializer
/// only when something first reaches that module. For an executable, this generator emits code that names one type
/// from every project reference, so the runtime can reach each of their modules through <c>typeof(...).Module</c>
/// instead of through the dependency context and <c>Assembly.Load</c>, neither of which works in single-file or
/// trimmed applications.
/// </para>
/// <para>
/// Project references are those the <c>Cratis.Arc.Core</c> build targets report through the
/// <c>CratisArcProjectReferences</c> property. When the property is absent - the targets were not imported - nothing
/// is emitted and Arc falls back to the runtime dependency context.
/// </para>
/// </remarks>
[Generator]
public class ProjectReferenceModulesGenerator : IIncrementalGenerator
{
    /// <summary>
    /// The analyzer config key carrying the project references reported by the build targets.
    /// </summary>
    public const string ProjectReferencesProperty = "build_property.CratisArcProjectReferences";

    /// <summary>
    /// The hint name of the generated source.
    /// </summary>
    public const string HintName = "ProjectReferenceModules.g.cs";

    const string RegistrationTypeName = "Cratis.Arc.ProjectReferenceModuleInitializers";

    static readonly HashSet<string> _excludedAttributes = new(StringComparer.Ordinal)
    {
        "System.ObsoleteAttribute",
        "Microsoft.CodeAnalysis.EmbeddedAttribute",
        "System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute"
    };

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var projectReferences = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            options.GlobalOptions.TryGetValue(ProjectReferencesProperty, out var value) ? value : null);

        var source = context.CompilationProvider
            .Combine(projectReferences)
            .Select(static (input, _) => GenerateSource(input.Left, input.Right));

        context.RegisterSourceOutput(source, static (output, text) =>
        {
            if (text is not null)
            {
                output.AddSource(HintName, text);
            }
        });
    }

    static string? GenerateSource(Compilation compilation, string? projectReferences)
    {
        if (projectReferences is null ||
            compilation.Options.OutputKind is not (OutputKind.ConsoleApplication or OutputKind.WindowsApplication or OutputKind.WindowsRuntimeApplication) ||
            compilation.GetTypeByMetadataName(RegistrationTypeName) is null)
        {
            return null;
        }

        var projectReferenceNames = ParseProjectReferences(projectReferences);
        if (projectReferenceNames is null)
        {
            return null;
        }

        var reachableTypes = new List<string>();
        var assembliesWithoutReachableTypes = new List<string>();

        foreach (var reference in compilation.References.OfType<PortableExecutableReference>())
        {
            if (reference.FilePath is null ||
                !projectReferenceNames.Contains(Path.GetFileNameWithoutExtension(reference.FilePath)) ||
                compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assembly ||
                SymbolEqualityComparer.Default.Equals(assembly, compilation.Assembly))
            {
                continue;
            }

            var type = IsGloballyVisible(reference) ? FindReachableType(compilation, assembly.GlobalNamespace) : null;
            if (type is null)
            {
                assembliesWithoutReachableTypes.Add(assembly.Identity.Name);
            }
            else
            {
                reachableTypes.Add(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }
        }

        reachableTypes.Sort(StringComparer.Ordinal);
        assembliesWithoutReachableTypes.Sort(StringComparer.Ordinal);

        var sb = new StringBuilder()
            .AppendLine("// <auto-generated/>")
            .AppendLine("#pragma warning disable")
            .AppendLine("namespace Cratis.Arc.Generated;")
            .AppendLine()
            .AppendLine("/// <summary>")
            .AppendLine("/// Compile-time generated registration of the project reference modules. Do not modify.")
            .AppendLine("/// </summary>")
            .AppendLine("file static class ProjectReferenceModules")
            .AppendLine("{")
            .AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]")
            .AppendLine("    internal static void Register() =>")
            .Append("        global::Cratis.Arc.ProjectReferenceModuleInitializers.Register(RunModuleInitializers, ")
            .Append(assembliesWithoutReachableTypes.Count == 0
                ? "global::System.Array.Empty<string>()"
                : $"new string[] {{ {string.Join(", ", assembliesWithoutReachableTypes.Select(ToStringLiteral))} }}")
            .AppendLine(");")
            .AppendLine()
            .AppendLine("    static void RunModuleInitializers()")
            .AppendLine("    {");

        foreach (var type in reachableTypes)
        {
            sb.Append("        global::System.Runtime.CompilerServices.RuntimeHelpers.RunModuleConstructor(typeof(")
                .Append(type)
                .AppendLine(").Module.ModuleHandle);");
        }

        return sb
            .AppendLine("    }")
            .AppendLine("}")
            .ToString();
    }

    static HashSet<string>? ParseProjectReferences(string projectReferences)
    {
        // "<count>|<name>|<name>..." - a list that does not match its count was cut short on the way here, and
        // registering only part of the project references would hide the rest from the runtime fallback.
        var parts = projectReferences.Split('|');
        if (!int.TryParse(parts[0].Trim(), NumberStyles.None, CultureInfo.InvariantCulture, out var count))
        {
            return null;
        }

        var names = parts.Skip(1).Select(_ => _.Trim()).Where(_ => _.Length > 0).ToArray();
        return names.Length == count ? new HashSet<string>(names, StringComparer.OrdinalIgnoreCase) : null;
    }

    static bool IsGloballyVisible(MetadataReference reference) =>
        reference.Properties.Aliases.IsDefaultOrEmpty || reference.Properties.Aliases.Contains("global");

    static INamedTypeSymbol? FindReachableType(Compilation compilation, INamespaceSymbol @namespace)
    {
        return @namespace.GetTypeMembers()
                .OrderBy(_ => _.MetadataName, StringComparer.Ordinal)
                .FirstOrDefault(_ => IsReachable(compilation, _)) ??
            @namespace.GetNamespaceMembers()
                .OrderBy(_ => _.Name, StringComparer.Ordinal)
                .Select(_ => FindReachableType(compilation, _))
                .FirstOrDefault(_ => _ is not null);
    }

    static bool IsReachable(Compilation compilation, INamedTypeSymbol type) =>
        !type.IsGenericType &&
        type.CanBeReferencedByName &&
        compilation.IsSymbolAccessibleWithin(type, compilation.Assembly) &&
        !type.GetAttributes().Any(_ => _excludedAttributes.Contains(_.AttributeClass?.ToDisplayString() ?? string.Empty)) &&
        SymbolEqualityComparer.Default.Equals(compilation.GetTypeByMetadataName(GetMetadataName(type)), type);

    static string GetMetadataName(INamedTypeSymbol type)
    {
        var name = type.MetadataName;
        for (var @namespace = type.ContainingNamespace; !@namespace.IsGlobalNamespace; @namespace = @namespace.ContainingNamespace)
        {
            name = $"{@namespace.MetadataName}.{name}";
        }

        return name;
    }

    static string ToStringLiteral(string value) =>
        $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
}
