<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Cratis.Arc.ProxyGenerator.Specs.ReferencedConceptCommand</AssemblyName>
        <RootNamespace>Cratis.Arc.ProxyGenerator.Specs.ReferencedConceptCommand</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../../../Arc.Core/Arc.Core.csproj" />
        <ProjectReference Include="../CommandResponseHandlerDependency/CommandResponseHandlerDependency.csproj" />
    </ItemGroup>
</Project>
