// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.AuthenticationQueries.AuthenticationQueryItem, Samples.Features.AuthenticationQueries.AuthenticationQueryItem, Samples.Features.AuthenticationQueries.AuthenticationQueryItem. Time: 2026-10-03T11:14:56.9415300Z. Hash: 54319BA400D9402DDB61AA6E9FDB1F98A8AB5BBBC058A9801848C308ECCC150F
// **DO NOT EDIT** - This file is an automatically generated file.
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { ObservableQueryWhen, useObservableQuery, useSuspenseObservableQuery } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

export class Anonymous extends ObservableQueryFor<AuthenticationQueryItem> {
    readonly route: string = '/api/features/authentication-queries/anonymous';
    readonly queryName: string = 'Samples.Features.AuthenticationQueries.AuthenticationQueryItem.Anonymous';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: AuthenticationQueryItem = {} as AuthenticationQueryItem;

    constructor() {
        super(AuthenticationQueryItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useObservableQuery<AuthenticationQueryItem, Anonymous>(Anonymous);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useSuspenseObservableQuery<AuthenticationQueryItem, Anonymous>(Anonymous);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Anonymous, AuthenticationQueryItem> {
        return new ObservableQueryWhen<Anonymous, AuthenticationQueryItem>(Anonymous, condition);
    }
}

export class Authenticated extends ObservableQueryFor<AuthenticationQueryItem> {
    readonly route: string = '/api/features/authentication-queries/authenticated';
    readonly queryName: string = 'Samples.Features.AuthenticationQueries.AuthenticationQueryItem.Authenticated';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: AuthenticationQueryItem = {} as AuthenticationQueryItem;

    constructor() {
        super(AuthenticationQueryItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useObservableQuery<AuthenticationQueryItem, Authenticated>(Authenticated);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useSuspenseObservableQuery<AuthenticationQueryItem, Authenticated>(Authenticated);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Authenticated, AuthenticationQueryItem> {
        return new ObservableQueryWhen<Authenticated, AuthenticationQueryItem>(Authenticated, condition);
    }
}

export class AuthenticationQueryItem {
    @field(String)
    message!: string;
}
