// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.QueryShowcase.ShowcaseItem. Time: 2026-10-09T23:44:03.6945020Z. Hash: 676AC65F9117F318BD6A417AA33318789A509FFC412718BEF5FCE2F932AF81ED
// **DO NOT EDIT** - This file is an automatically generated file.
import { ChangeSet, ObservableQueryFor, Paging, QueryResultWithState, Sorting, SortingActions, SortingActionsForObservableQuery } from '@cratis/arc/queries';
import { ObservableQueryWhen, SetPage, SetPageSize, SetSorting, useChangeStream, useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShowcaseItem } from './ShowcaseItem';

class AllSortBy {
    private _id: SortingActionsForObservableQuery<ShowcaseItem[]>;
    private _name: SortingActionsForObservableQuery<ShowcaseItem[]>;
    private _updatedAt: SortingActionsForObservableQuery<ShowcaseItem[]>;

    constructor(readonly query: All) {
        this._id = new SortingActionsForObservableQuery<ShowcaseItem[]>('id', query);
        this._name = new SortingActionsForObservableQuery<ShowcaseItem[]>('name', query);
        this._updatedAt = new SortingActionsForObservableQuery<ShowcaseItem[]>('updatedAt', query);
    }

    get id(): SortingActionsForObservableQuery<ShowcaseItem[]> {
        return this._id;
    }
    get name(): SortingActionsForObservableQuery<ShowcaseItem[]> {
        return this._name;
    }
    get updatedAt(): SortingActionsForObservableQuery<ShowcaseItem[]> {
        return this._updatedAt;
    }
}

class AllSortByWithoutQuery {
    private _id: SortingActions  = new SortingActions('id');
    private _name: SortingActions  = new SortingActions('name');
    private _updatedAt: SortingActions  = new SortingActions('updatedAt');

    get id(): SortingActions {
        return this._id;
    }
    get name(): SortingActions {
        return this._name;
    }
    get updatedAt(): SortingActions {
        return this._updatedAt;
    }
}


export class All extends ObservableQueryFor<ShowcaseItem[]> {
    readonly route: string = '/api/features/query-showcase/all';
    readonly queryName: string = 'Samples.Features.QueryShowcase.ShowcaseItem.All';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(ShowcaseItem, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting] {
        return useObservableQuery<ShowcaseItem[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ShowcaseItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting] {
        return useSuspenseObservableQuery<ShowcaseItem[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ShowcaseItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: ShowcaseItem) => unknown, sorting?: Sorting): ChangeSet<ShowcaseItem> {
        return useChangeStream<ShowcaseItem, All>(All, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, ShowcaseItem[]> {
        return new ObservableQueryWhen<All, ShowcaseItem[]>(All, condition);
    }
}
