// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.QueryShowcase.ShowcaseItem. Time: 2026-10-03T11:15:01.4419310Z. Hash: 705BAAC9FB0365A461F68D0CF92084813AAE0D294265FA5460D512B79D7DC23A
// **DO NOT EDIT** - This file is an automatically generated file.
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { PerformQuery, QueryWhen, SetSorting, useQuery, useSuspenseQuery } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShowcaseItem } from './ShowcaseItem';


export interface ByIdParameters {
    id: number;
}


export class ById extends QueryFor<ShowcaseItem, ByIdParameters> {
    readonly route: string = '/api/features/query-showcase/by-id';
    readonly queryName: string = 'Samples.Features.QueryShowcase.ShowcaseItem.ById';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem = {} as ShowcaseItem;

    constructor() {
        super(ShowcaseItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', Number, false),
    ];

    id!: number;


    static use(args?: ByIdParameters): [QueryResultWithState<ShowcaseItem>, PerformQuery<ByIdParameters>, SetSorting] {
        return useQuery<ShowcaseItem, ById, ByIdParameters>(ById, args);
    }

    static useSuspense(args?: ByIdParameters): [QueryResultWithState<ShowcaseItem>, PerformQuery<ByIdParameters>, SetSorting] {
        return useSuspenseQuery<ShowcaseItem, ById, ByIdParameters>(ById, args);
    }

    static when(condition: boolean): QueryWhen<ById, ShowcaseItem, ByIdParameters> {
        return new QueryWhen<ById, ShowcaseItem, ByIdParameters>(ById, condition);
    }
}
