// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.QueryShowcase.ShowcaseItem. Time: 2026-10-09T23:44:03.6945020Z. Hash: 928887D67BA1305CE935FF40FFE619DA328D62BCB5E9C086F55A2E0D2A9ADAB6
// **DO NOT EDIT** - This file is an automatically generated file.
import { Paging, QueryFor, QueryResultWithState, Sorting, SortingActions, SortingActionsForQuery } from '@cratis/arc/queries';
import { PerformQuery, QueryWhen, SetPage, SetPageSize, SetSorting, useQuery, useQueryWithPaging, useSuspenseQuery, useSuspenseQueryWithPaging } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShowcaseItem } from './ShowcaseItem';

class GetAllSortBy {
    private _id: SortingActionsForQuery<ShowcaseItem[]>;
    private _name: SortingActionsForQuery<ShowcaseItem[]>;
    private _updatedAt: SortingActionsForQuery<ShowcaseItem[]>;

    constructor(readonly query: GetAll) {
        this._id = new SortingActionsForQuery<ShowcaseItem[]>('id', query);
        this._name = new SortingActionsForQuery<ShowcaseItem[]>('name', query);
        this._updatedAt = new SortingActionsForQuery<ShowcaseItem[]>('updatedAt', query);
    }

    get id(): SortingActionsForQuery<ShowcaseItem[]> {
        return this._id;
    }
    get name(): SortingActionsForQuery<ShowcaseItem[]> {
        return this._name;
    }
    get updatedAt(): SortingActionsForQuery<ShowcaseItem[]> {
        return this._updatedAt;
    }
}

class GetAllSortByWithoutQuery {
    private _id: SortingActions  = new SortingActions('id');
    private _name: SortingActions  = new SortingActions('name');
    private _updatedAt: SortingActions  = new SortingActions('updatedAt');

    get id(): SortingActions {
        return this._id;
    }
    get name(): SortingActions {
        return this._name;
    }
    get updatedAt(): SortingActions {
        return this._updatedAt;
    }
}


export class GetAll extends QueryFor<ShowcaseItem[]> {
    readonly route: string = '/api/features/query-showcase/get-all';
    readonly queryName: string = 'Samples.Features.QueryShowcase.ShowcaseItem.GetAll';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem[] = [];
    private readonly _sortBy: GetAllSortBy;
    private static readonly _sortBy: GetAllSortByWithoutQuery = new GetAllSortByWithoutQuery();

    constructor() {
        super(ShowcaseItem, true);
        this._sortBy = new GetAllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): GetAllSortBy {
        return this._sortBy;
    }

    static get sortBy(): GetAllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, PerformQuery, SetSorting] {
        return useQuery<ShowcaseItem[], GetAll>(GetAll, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<ShowcaseItem[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, PerformQuery, SetSorting] {
        return useSuspenseQuery<ShowcaseItem[], GetAll>(GetAll, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<ShowcaseItem[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): QueryWhen<GetAll, ShowcaseItem[]> {
        return new QueryWhen<GetAll, ShowcaseItem[]>(GetAll, condition);
    }
}
