// @generated by Cratis. Source: Samples.Features.QueryShowcase.ShowcaseItem. Time: 2026-10-01T10:15:47.5033350Z. Hash: 92627583E2F24D6B4022C103A9DCE7F050FE95103FD1486DFEA58D3E3EEDFB2C
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShowcaseItem } from './ShowcaseItem';



export class Latest extends ObservableQueryFor<ShowcaseItem> {
    readonly route: string = '/api/features/query-showcase/latest';
    readonly queryName: string = 'Samples.Features.QueryShowcase.ShowcaseItem.Latest';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem = {} as ShowcaseItem;

    constructor() {
        super(ShowcaseItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<ShowcaseItem>] {
        const [result] = useObservableQuery<ShowcaseItem, Latest>(Latest);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<ShowcaseItem>] {
        const [result] = useSuspenseObservableQuery<ShowcaseItem, Latest>(Latest);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Latest, ShowcaseItem> {
        return new ObservableQueryWhen<Latest, ShowcaseItem>(Latest, condition);
    }
}
