// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.QueryShowcase.ShowcaseItem. Time: 2026-10-03T11:15:01.4419310Z. Hash: E6A25E484B9EEE55413D4E493EA0A7307F8C21787992F783BA81C34402D723F2
// **DO NOT EDIT** - This file is an automatically generated file.
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { ObservableQueryWhen, useObservableQuery, useSuspenseObservableQuery } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShowcaseItem } from './ShowcaseItem';



export class Latest extends ObservableQueryFor<ShowcaseItem> {
    readonly route: string = '/api/features/query-showcase/latest';
    readonly queryName: string = 'Samples.Features.QueryShowcase.ShowcaseItem.Latest';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem = {} as ShowcaseItem;

    constructor() {
        super(ShowcaseItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<ShowcaseItem>] {
        const [result] = useObservableQuery<ShowcaseItem, Latest>(Latest);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<ShowcaseItem>] {
        const [result] = useSuspenseObservableQuery<ShowcaseItem, Latest>(Latest);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Latest, ShowcaseItem> {
        return new ObservableQueryWhen<Latest, ShowcaseItem>(Latest, condition);
    }
}
