// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.QueryShowcase.ShowcaseItem. Time: 2026-10-03T11:15:01.4419310Z. Hash: 00BBBD17950B001205D9724956F2D3C171ED2CB04A3DD84910E6E70D2C6541DB
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';

export class ShowcaseItem {
    @field(Number)
    id!: number;
    @field(String)
    name!: string;
    @field(Date)
    updatedAt!: Date;
}
