// @generated by Cratis. Source: TestApps.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus, TestApps.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus. Time: 2026-09-06T08:22:29.2467120Z. Hash: B5710FC06A2BD151842F9228ECA25D36CC2F19ABDD547CF4EB75E1A2F8BE97DE
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

export class Secured extends QueryFor<CrossCuttingAuthorizationStatus> {
    readonly route: string = '/api/features/cross-cutting-authorization/secured';
    readonly queryName: string = 'TestApps.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus.Secured';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: CrossCuttingAuthorizationStatus = {} as CrossCuttingAuthorizationStatus;

    constructor() {
        super(CrossCuttingAuthorizationStatus, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<CrossCuttingAuthorizationStatus>, PerformQuery, SetSorting] {
        return useQuery<CrossCuttingAuthorizationStatus, Secured>(Secured);
    }

    static useSuspense(): [QueryResultWithState<CrossCuttingAuthorizationStatus>, PerformQuery, SetSorting] {
        return useSuspenseQuery<CrossCuttingAuthorizationStatus, Secured>(Secured);
    }

    static when(condition: boolean): QueryWhen<Secured, CrossCuttingAuthorizationStatus> {
        return new QueryWhen<Secured, CrossCuttingAuthorizationStatus>(Secured, condition);
    }
}

export class CrossCuttingAuthorizationStatus {
    @field(String)
    message!: string;
    @field(Date)
    checkedAt!: Date;
}
