// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ChangeStream.ChangeStreamItem. Time: 2026-10-09T23:44:03.6945020Z. Hash: 5060C7EDBF2D278E4803E7914D19F92DA1E253223DEAC18E1A6AC1275D3FD416
// **DO NOT EDIT** - This file is an automatically generated file.
import { ChangeSet, ObservableQueryFor, Paging, QueryResultWithState, Sorting, SortingActions, SortingActionsForObservableQuery } from '@cratis/arc/queries';
import { ObservableQueryWhen, SetPage, SetPageSize, SetSorting, useChangeStream, useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ChangeStreamItem } from './ChangeStreamItem';

class AllSortBy {
    private _id: SortingActionsForObservableQuery<ChangeStreamItem[]>;
    private _label: SortingActionsForObservableQuery<ChangeStreamItem[]>;
    private _value: SortingActionsForObservableQuery<ChangeStreamItem[]>;

    constructor(readonly query: All) {
        this._id = new SortingActionsForObservableQuery<ChangeStreamItem[]>('id', query);
        this._label = new SortingActionsForObservableQuery<ChangeStreamItem[]>('label', query);
        this._value = new SortingActionsForObservableQuery<ChangeStreamItem[]>('value', query);
    }

    get id(): SortingActionsForObservableQuery<ChangeStreamItem[]> {
        return this._id;
    }
    get label(): SortingActionsForObservableQuery<ChangeStreamItem[]> {
        return this._label;
    }
    get value(): SortingActionsForObservableQuery<ChangeStreamItem[]> {
        return this._value;
    }
}

class AllSortByWithoutQuery {
    private _id: SortingActions  = new SortingActions('id');
    private _label: SortingActions  = new SortingActions('label');
    private _value: SortingActions  = new SortingActions('value');

    get id(): SortingActions {
        return this._id;
    }
    get label(): SortingActions {
        return this._label;
    }
    get value(): SortingActions {
        return this._value;
    }
}


export class All extends ObservableQueryFor<ChangeStreamItem[]> {
    readonly route: string = '/api/features/change-stream/all';
    readonly queryName: string = 'Samples.Features.ChangeStream.ChangeStreamItem.All';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ChangeStreamItem[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(ChangeStreamItem, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ChangeStreamItem[]>, SetSorting] {
        return useObservableQuery<ChangeStreamItem[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ChangeStreamItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ChangeStreamItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ChangeStreamItem[]>, SetSorting] {
        return useSuspenseObservableQuery<ChangeStreamItem[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ChangeStreamItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ChangeStreamItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: ChangeStreamItem) => unknown, sorting?: Sorting): ChangeSet<ChangeStreamItem> {
        return useChangeStream<ChangeStreamItem, All>(All, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, ChangeStreamItem[]> {
        return new ObservableQueryWhen<All, ChangeStreamItem[]>(All, condition);
    }
}
