// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ChangeStream.RemoveChangeStreamItem. Time: 2026-10-03T11:15:01.4419310Z. Hash: 769B42401BAE07199FA997D1A61AFF3B3070587D74B21F6851DE582CE48FC100
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IRemoveChangeStreamItem {
    id?: number;
}


export class RemoveChangeStreamItem extends Command<IRemoveChangeStreamItem> implements IRemoveChangeStreamItem {
    readonly route: string = '/api/features/change-stream/remove-change-stream-item';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
    ];

    private _id!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this._id;
    }

    set id(value: number) {
        this._id = value;
        this.propertyChanged('id');
    }

    static use(initialValues?: IRemoveChangeStreamItem): [RemoveChangeStreamItem, SetCommandValues<IRemoveChangeStreamItem>, ClearCommandValues] {
        return useCommand<RemoveChangeStreamItem, IRemoveChangeStreamItem>(RemoveChangeStreamItem, initialValues);
    }
}
