// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ChangeStream.UpdateChangeStreamItem. Time: 2026-10-03T11:15:01.4419310Z. Hash: 17AE930E1D6BF4C74C87E8594632D0F95743F8B66D328AE1D49BE7208554E99A
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IUpdateChangeStreamItem {
    id?: number;
    label?: string;
    value?: number;
}


export class UpdateChangeStreamItem extends Command<IUpdateChangeStreamItem> implements IUpdateChangeStreamItem {
    readonly route: string = '/api/features/change-stream/update-change-stream-item';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
        new PropertyDescriptor('label', String, false),
        new PropertyDescriptor('value', Number, false),
    ];

    private _id!: number;
    private _label!: string;
    private _value!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this._id;
    }

    set id(value: number) {
        this._id = value;
        this.propertyChanged('id');
    }
    get label(): string {
        return this._label;
    }

    set label(value: string) {
        this._label = value;
        this.propertyChanged('label');
    }
    get value(): number {
        return this._value;
    }

    set value(value: number) {
        this._value = value;
        this.propertyChanged('value');
    }

    static use(initialValues?: IUpdateChangeStreamItem): [UpdateChangeStreamItem, SetCommandValues<IUpdateChangeStreamItem>, ClearCommandValues] {
        return useCommand<UpdateChangeStreamItem, IUpdateChangeStreamItem>(UpdateChangeStreamItem, initialValues);
    }
}
