// @generated by Cratis. Source: Samples.Features.Ticker.Ticker, Samples.Features.Ticker.Ticker. Time: 2026-10-01T10:15:45.6865360Z. Hash: AC105B985E46FEB8E5D7B5F0BF7C1E57F3A4521C1000856B851499A2AE5A3571
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

export class Observe extends ObservableQueryFor<Ticker> {
    readonly route: string = '/api/features/ticker/observe';
    readonly queryName: string = 'Samples.Features.Ticker.Ticker.Observe';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Ticker = {} as Ticker;

    constructor() {
        super(Ticker, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<Ticker>] {
        const [result] = useObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<Ticker>] {
        const [result] = useSuspenseObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Observe, Ticker> {
        return new ObservableQueryWhen<Observe, Ticker>(Observe, condition);
    }
}

export class Ticker {
    @field(Number)
    count!: number;
    @field(Date)
    lastUpdated!: Date;
}
