import { Linter } from 'eslint';
import { describe, expect, it } from 'vitest';
import { isGeneratedProxy, skipGeneratedProxies } from '../lib/skipGeneratedProxies.js';

const linter = new Linter();

// A single core rule that is easy to trip (a statement without a semicolon), applied
// through the skip processor. Generated files should report nothing; hand-written files
// should still be linted.
const config = [
    {
        files: ['**/*.ts'],
        processor: skipGeneratedProxies,
        rules: { semi: ['error', 'always'] },
    },
];

const lint = code => linter.verify(code, config, { filename: 'sample.ts' });
const fix = code => linter.verifyAndFix(code, config, { filename: 'sample.ts' });

const GENERATED = '// @generated by Cratis. Source: Foo. Hash: ABC\nconst a = 1\n';
const BANNER_ONLY = [
    '/*-------------------------------------------------------',
    ' *  **DO NOT EDIT** - This file is an automatically generated file.',
    ' *------------------------------------------------------*/',
    'const a = 1',
    '',
].join('\n');
const HANDWRITTEN = 'const a = 1\n';

describe('isGeneratedProxy', () => {
    it('recognises the @generated header', () => {
        expect(isGeneratedProxy(GENERATED)).toBe(true);
    });

    it('recognises the DO NOT EDIT banner as a fallback', () => {
        expect(isGeneratedProxy(BANNER_ONLY)).toBe(true);
    });

    it('does not match hand-written source', () => {
        expect(isGeneratedProxy(HANDWRITTEN)).toBe(false);
    });
});

describe('skip-generated-proxies processor', () => {
    it('reports nothing for a generated proxy', () => {
        expect(lint(GENERATED)).toHaveLength(0);
    });

    it('reports nothing for a banner-only generated file', () => {
        expect(lint(BANNER_ONLY)).toHaveLength(0);
    });

    it('still lints hand-written source (identical content, no header)', () => {
        const messages = lint(HANDWRITTEN);
        expect(messages.map(message => message.ruleId)).toContain('semi');
    });

    it('keeps --fix working on hand-written source', () => {
        expect(fix(HANDWRITTEN).output).toBe('const a = 1;\n');
    });

    it('never rewrites a generated proxy under --fix', () => {
        expect(fix(GENERATED).output).toBe(GENERATED);
    });
});
