import { Linter } from 'eslint';
import { describe, expect, it } from 'vitest';
import { isGeneratedProxy, skipGeneratedProxies } from '../lib/skipGeneratedProxies.js';

const linter = new Linter();

// A single core rule that is easy to trip (a statement without a semicolon), applied
// through the skip processor. Generated files should report nothing; hand-written files
// should still be linted.
const config = [
    {
        files: ['**/*.ts'],
        processor: skipGeneratedProxies,
        rules: { semi: ['error', 'always'] },
    },
];

const lint = code => linter.verify(code, config, { filename: 'sample.ts' });
const fix = code => linter.verifyAndFix(code, config, { filename: 'sample.ts' });

const GENERATED = '// @generated by Cratis. Source: Foo. Hash: ABC\nconst a = 1\n';
const LICENSE_FIRST = [
    '// Copyright (c) Cratis. All rights reserved.',
    '// Licensed under the MIT license. See LICENSE file in the project root for full license information.',
    '',
    GENERATED,
].join('\n');
const BANNER_ONLY = [
    '/*-------------------------------------------------------',
    ' *  **DO NOT EDIT** - This file is an automatically generated file.',
    ' *------------------------------------------------------*/',
    'const a = 1',
    '',
].join('\n');
const HANDWRITTEN = 'const a = 1\n';
const unsafeHeaders = ['\n', '\r\n'].flatMap(newline => [
    [LICENSE_FIRST.split('\n')[0], LICENSE_FIRST.split('\n')[1], 'const example = `', GENERATED.split('\n')[0], '`', 'const a = 1', ''],
    ['// Copyright (c) Cratis. Not the standard copyright.', LICENSE_FIRST.split('\n')[1], '', GENERATED.split('\n')[0], 'const a = 1', ''],
    [LICENSE_FIRST.split('\n')[0], '// Not the standard license', '', GENERATED.split('\n')[0], 'const a = 1', ''],
].map(lines => lines.join(newline)));

describe('isGeneratedProxy', () => {
    it.each(unsafeHeaders)('rejects unsafe fourth-line envelopes: %s', code => {
        expect(isGeneratedProxy(code)).toBe(false);
    });

    it('recognises the CRLF license-first marker', () => {
        expect(isGeneratedProxy(LICENSE_FIRST.replaceAll('\n', '\r\n'))).toBe(true);
    });
    it('recognises the @generated header', () => {
        expect(isGeneratedProxy(GENERATED)).toBe(true);
    });

    it('recognises the license-first marker', () => {
        expect(isGeneratedProxy(LICENSE_FIRST)).toBe(true);
    });

    it('does not match a marker inside a string literal', () => {
        expect(isGeneratedProxy(`const marker = '${GENERATED.split('\n')[0]}';`)).toBe(false);
    });

    it('does not match a marker beyond the header', () => {
        expect(isGeneratedProxy(`// Copyright (c) Cratis.\n\n\nconst value = 1;\n${GENERATED}`)).toBe(false);
    });

    it('recognises the DO NOT EDIT banner as a fallback', () => {
        expect(isGeneratedProxy(BANNER_ONLY)).toBe(true);
    });

    it('does not match hand-written source', () => {
        expect(isGeneratedProxy(HANDWRITTEN)).toBe(false);
    });
});

describe('skip-generated-proxies processor', () => {
    it.each(unsafeHeaders)('lints and fixes authored unsafe envelopes: %s', code => {
        expect(lint(code).map(message => message.ruleId)).toContain('semi');
        const result = fix(code);
        expect(result.fixed).toBe(true);
        expect(result.output).toContain('const a = 1;');
        expect(lint(result.output)).toHaveLength(0);
    });
    it('reports nothing for a generated proxy', () => {
        expect(lint(GENERATED)).toHaveLength(0);
    });

    it('skips and never rewrites a license-first proxy', () => {
        expect(lint(LICENSE_FIRST)).toHaveLength(0);
        expect(fix(LICENSE_FIRST).output).toBe(LICENSE_FIRST);
    });

    it('reports nothing for a banner-only generated file', () => {
        expect(lint(BANNER_ONLY)).toHaveLength(0);
    });

    it('still lints hand-written source (identical content, no header)', () => {
        const messages = lint(HANDWRITTEN);
        expect(messages.map(message => message.ruleId)).toContain('semi');
    });

    it('keeps --fix working on hand-written source', () => {
        expect(fix(HANDWRITTEN).output).toBe('const a = 1;\n');
    });

    it('never rewrites a generated proxy under --fix', () => {
        expect(fix(GENERATED).output).toBe(GENERATED);
    });
});
