// @generated by Cratis. Source: TestApps.Features.ChangeStream.AddChangeStreamItem. Time: 2026-04-12T08:36:37.3696620Z. Hash: 9B69DD9DB1EADA0AA2D8C883A69AE687DF60744DA9C433549FF1A6AE10821EB8
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IAddChangeStreamItem {
    id?: number;
    label?: string;
    value?: number;
}

export class AddChangeStreamItemValidator extends CommandValidator<IAddChangeStreamItem> {
    constructor() {
        super();
    }
}

export class AddChangeStreamItem extends Command<IAddChangeStreamItem> implements IAddChangeStreamItem {
    readonly route: string = '/api/features/change-stream/add-change-stream-item';
    readonly validation: CommandValidator = new AddChangeStreamItemValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
        new PropertyDescriptor('label', String, false),
        new PropertyDescriptor('value', Number, false),
    ];

    private _id!: number;
    private _label!: string;
    private _value!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this._id;
    }

    set id(value: number) {
        this._id = value;
        this.propertyChanged('id');
    }
    get label(): string {
        return this._label;
    }

    set label(value: string) {
        this._label = value;
        this.propertyChanged('label');
    }
    get value(): number {
        return this._value;
    }

    set value(value: number) {
        this._value = value;
        this.propertyChanged('value');
    }

    static use(initialValues?: IAddChangeStreamItem): [AddChangeStreamItem, SetCommandValues<IAddChangeStreamItem>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<AddChangeStreamItem, IAddChangeStreamItem>(AddChangeStreamItem, initialValues);
    }
}
