// @generated by Cratis. Source: TestApps.Features.ChangeStream.ChangeStreamItem. Time: 2026-07-19T23:32:51.1097230Z. Hash: 0A4604EEDAD01E1FA2326ECC5F1A53B9384FE2B185CA4DD0B93F9743ADBEEDE1
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, QueryValidator, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ChangeStreamItem } from './ChangeStreamItem';

class AllSortBy {

    constructor(readonly query: All) {
    }

}

class AllSortByWithoutQuery {

}

export class AllValidator extends QueryValidator<object> {
    constructor() {
        super();
    }
}

export class All extends ObservableQueryFor<ChangeStreamItem[]> {
    readonly route: string = '/api/features/change-stream/all';
    readonly queryName: string = 'TestApps.Features.ChangeStream.ChangeStreamItem.All';
    readonly validation: QueryValidator = new AllValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ChangeStreamItem[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(ChangeStreamItem, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ChangeStreamItem[]>, SetSorting] {
        return useObservableQuery<ChangeStreamItem[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ChangeStreamItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ChangeStreamItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ChangeStreamItem[]>, SetSorting] {
        return useSuspenseObservableQuery<ChangeStreamItem[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ChangeStreamItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ChangeStreamItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: ChangeStreamItem) => unknown, sorting?: Sorting): ChangeSet<ChangeStreamItem> {
        return useChangeStream<ChangeStreamItem, All>(All, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, ChangeStreamItem[]> {
        return new ObservableQueryWhen<All, ChangeStreamItem[]>(All, condition);
    }
}
