// @generated by Cratis. Source: TestApps.Features.ChangeStream.ChangeStreamItem. Time: 2026-04-12T08:36:37.3696620Z. Hash: 506CE7A6F63B256AD6DF1D35D16118C17044E2494239F06014AAC0DAD9B46807
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

export class ChangeStreamItem {
    @field(Number)
    id!: number;
    @field(String)
    label!: string;
    @field(Number)
    value!: number;
}
