// @generated by Cratis. Source: TestApps.Features.ChangeStream.RemoveChangeStreamItem. Time: 2026-04-12T08:36:37.3696620Z. Hash: 51E058DB49555995F124810282132D6F649E51533AC8C6B0E012FC02B49AFC13
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IRemoveChangeStreamItem {
    id?: number;
}

export class RemoveChangeStreamItemValidator extends CommandValidator<IRemoveChangeStreamItem> {
    constructor() {
        super();
    }
}

export class RemoveChangeStreamItem extends Command<IRemoveChangeStreamItem> implements IRemoveChangeStreamItem {
    readonly route: string = '/api/features/change-stream/remove-change-stream-item';
    readonly validation: CommandValidator = new RemoveChangeStreamItemValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
    ];

    private _id!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this._id;
    }

    set id(value: number) {
        this._id = value;
        this.propertyChanged('id');
    }

    static use(initialValues?: IRemoveChangeStreamItem): [RemoveChangeStreamItem, SetCommandValues<IRemoveChangeStreamItem>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RemoveChangeStreamItem, IRemoveChangeStreamItem>(RemoveChangeStreamItem, initialValues);
    }
}
