// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: AspNetCore.Features.Reservations.ReserveTable. Time: 2026-10-03T11:15:01.4419310Z. Hash: 7CC9D115304C52113BC13DDEE6885BAF470B9495970E947C8D58B9C23551BB88
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IReserveTable {
    concurrency?: number;
    description?: string;
    guest?: string;
    reference?: string;
}


export class ReserveTable extends Command<IReserveTable> implements IReserveTable {
    readonly route: string = '/api/features/reservations';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('concurrency', Number, false),
        new PropertyDescriptor('description', String, false),
        new PropertyDescriptor('guest', String, false),
        new PropertyDescriptor('reference', String, false),
    ];

    private _concurrency!: number;
    private _description!: string;
    private _guest!: string;
    private _reference!: string;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get concurrency(): number {
        return this._concurrency;
    }

    set concurrency(value: number) {
        this._concurrency = value;
        this.propertyChanged('concurrency');
    }
    get description(): string {
        return this._description;
    }

    set description(value: string) {
        this._description = value;
        this.propertyChanged('description');
    }
    get guest(): string {
        return this._guest;
    }

    set guest(value: string) {
        this._guest = value;
        this.propertyChanged('guest');
    }
    get reference(): string {
        return this._reference;
    }

    set reference(value: string) {
        this._reference = value;
        this.propertyChanged('reference');
    }

    static use(initialValues?: IReserveTable): [ReserveTable, SetCommandValues<IReserveTable>, ClearCommandValues] {
        return useCommand<ReserveTable, IReserveTable>(ReserveTable, initialValues);
    }
}
