// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: AspNetCore.Features.Reservations.ReserveTable. Time: 2026-10-09T18:27:40.8705754Z. Hash: 1C499DF915858FCB7B75DE225587355432B18848D19837113E5C1986F1B4EFCD
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IReserveTable {
    concurrency?: number;
    description?: string;
    guest?: string;
    reference?: string;
}


export class ReserveTable extends Command<IReserveTable> implements IReserveTable {
    readonly route: string = '/api/features/reservations';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('concurrency', Number, false),
        new PropertyDescriptor('description', String, false),
        new PropertyDescriptor('guest', String, false),
        new PropertyDescriptor('reference', String, false),
    ];

    #concurrency!: number;
    #description!: string;
    #guest!: string;
    #reference!: string;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get concurrency(): number {
        return this.#concurrency;
    }

    set concurrency(value: number) {
        this.#concurrency = value;
        this.propertyChanged('concurrency');
    }
    get description(): string {
        return this.#description;
    }

    set description(value: string) {
        this.#description = value;
        this.propertyChanged('description');
    }
    get guest(): string {
        return this.#guest;
    }

    set guest(value: string) {
        this.#guest = value;
        this.propertyChanged('guest');
    }
    get reference(): string {
        return this.#reference;
    }

    set reference(value: string) {
        this.#reference = value;
        this.propertyChanged('reference');
    }

    static use(initialValues?: IReserveTable): [ReserveTable, SetCommandValues<IReserveTable>, ClearCommandValues] {
        return useCommand<ReserveTable, IReserveTable>(ReserveTable, initialValues);
    }
}
