// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ObservableCollectionWithGuid.AddObservableCollectionWithGuidItem. Time: 2026-10-03T11:15:01.4419310Z. Hash: 6C03083ABF8BA33AD8B3279EE106C64A26C19B6A33DD577C424F08F7188F617C
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface IAddObservableCollectionWithGuidItem {
    id?: Guid;
    label?: string;
}


export class AddObservableCollectionWithGuidItem extends Command<IAddObservableCollectionWithGuidItem> implements IAddObservableCollectionWithGuidItem {
    readonly route: string = '/api/features/observable-collection-with-guid/add-observable-collection-with-guid-item';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Guid, false),
        new PropertyDescriptor('label', String, false),
    ];

    private _id!: Guid;
    private _label!: string;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): Guid {
        return this._id;
    }

    set id(value: Guid) {
        this._id = value;
        this.propertyChanged('id');
    }
    get label(): string {
        return this._label;
    }

    set label(value: string) {
        this._label = value;
        this.propertyChanged('label');
    }

    static use(initialValues?: IAddObservableCollectionWithGuidItem): [AddObservableCollectionWithGuidItem, SetCommandValues<IAddObservableCollectionWithGuidItem>, ClearCommandValues] {
        return useCommand<AddObservableCollectionWithGuidItem, IAddObservableCollectionWithGuidItem>(AddObservableCollectionWithGuidItem, initialValues);
    }
}
