// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ObservableCollectionWithGuid.ObservableCollectionWithGuidItem. Time: 2026-10-03T11:15:01.4419310Z. Hash: ADB91E2617D32BC0850BB7515C60550121317F8D778A0153B425E47A9048A833
// **DO NOT EDIT** - This file is an automatically generated file.
import { ChangeSet, ObservableQueryFor, Paging, QueryResultWithState, Sorting } from '@cratis/arc/queries';
import { ObservableQueryWhen, SetPage, SetPageSize, SetSorting, useChangeStream, useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ObservableCollectionWithGuidItem } from './ObservableCollectionWithGuidItem';

class AllSortBy {

    constructor(readonly query: All) {
    }

}

class AllSortByWithoutQuery {

}


export class All extends ObservableQueryFor<ObservableCollectionWithGuidItem[]> {
    readonly route: string = '/api/features/observable-collection-with-guid/all';
    readonly queryName: string = 'Samples.Features.ObservableCollectionWithGuid.ObservableCollectionWithGuidItem.All';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ObservableCollectionWithGuidItem[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(ObservableCollectionWithGuidItem, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ObservableCollectionWithGuidItem[]>, SetSorting] {
        return useObservableQuery<ObservableCollectionWithGuidItem[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ObservableCollectionWithGuidItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ObservableCollectionWithGuidItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ObservableCollectionWithGuidItem[]>, SetSorting] {
        return useSuspenseObservableQuery<ObservableCollectionWithGuidItem[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ObservableCollectionWithGuidItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ObservableCollectionWithGuidItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: ObservableCollectionWithGuidItem) => unknown, sorting?: Sorting): ChangeSet<ObservableCollectionWithGuidItem> {
        return useChangeStream<ObservableCollectionWithGuidItem, All>(All, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, ObservableCollectionWithGuidItem[]> {
        return new ObservableQueryWhen<All, ObservableCollectionWithGuidItem[]>(All, condition);
    }
}
