// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus, Samples.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus. Time: 2026-10-03T11:14:56.9415300Z. Hash: A57C13E2EBBFA509A4E6A36839EEF3A9EC6A43CCD3A9CB224BE8A1200E91097F
// **DO NOT EDIT** - This file is an automatically generated file.
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { PerformQuery, QueryWhen, SetSorting, useQuery, useSuspenseQuery } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

export class Secured extends QueryFor<CrossCuttingAuthorizationStatus> {
    readonly route: string = '/api/features/cross-cutting-authorization/secured';
    readonly queryName: string = 'Samples.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus.Secured';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: CrossCuttingAuthorizationStatus = {} as CrossCuttingAuthorizationStatus;

    constructor() {
        super(CrossCuttingAuthorizationStatus, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<CrossCuttingAuthorizationStatus>, PerformQuery, SetSorting] {
        return useQuery<CrossCuttingAuthorizationStatus, Secured>(Secured);
    }

    static useSuspense(): [QueryResultWithState<CrossCuttingAuthorizationStatus>, PerformQuery, SetSorting] {
        return useSuspenseQuery<CrossCuttingAuthorizationStatus, Secured>(Secured);
    }

    static when(condition: boolean): QueryWhen<Secured, CrossCuttingAuthorizationStatus> {
        return new QueryWhen<Secured, CrossCuttingAuthorizationStatus>(Secured, condition);
    }
}

export class CrossCuttingAuthorizationStatus {
    @field(String)
    message!: string;
    @field(Date)
    checkedAt!: Date;
}
