// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.CrossCuttingAuthorization.RunSecuredCommand. Time: 2026-10-03T11:14:56.9415300Z. Hash: 5086256F2A76DC498DFE3808F4B618B28AF8B10B4AD14D77E74BF9A133ADCC12
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IRunSecuredCommand {
    message?: string;
}


export class RunSecuredCommand extends Command<IRunSecuredCommand, string> implements IRunSecuredCommand {
    readonly route: string = '/api/features/cross-cutting-authorization';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('message', String, false),
    ];

    private _message!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get message(): string {
        return this._message;
    }

    set message(value: string) {
        this._message = value;
        this.propertyChanged('message');
    }

    static use(initialValues?: IRunSecuredCommand): [RunSecuredCommand, SetCommandValues<IRunSecuredCommand>, ClearCommandValues] {
        return useCommand<RunSecuredCommand, IRunSecuredCommand, string>(RunSecuredCommand, initialValues);
    }
}
