// @generated by Cratis. Source: AspNetCore.LiveFeed. Time: 2026-03-22T09:12:01.2621591Z. Hash: BBF4D705D6B09F0C31994EBD162F91D655C2CE284D9394D36F8ACA17696E4120
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { LiveFeed } from './LiveFeed';

class AllSortBy {

    constructor(readonly query: All) {
    }

}

class AllSortByWithoutQuery {

}

export class All extends ObservableQueryFor<LiveFeed[]> {
    readonly route: string = '/api/asp-net-core/all';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: LiveFeed[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(LiveFeed, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useObservableQuery<LiveFeed[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<LiveFeed[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useSuspenseObservableQuery<LiveFeed[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<LiveFeed[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, LiveFeed[]> {
        return new ObservableQueryWhen<All, LiveFeed[]>(All, condition);
    }
}
