// @generated by Cratis. Source: AspNetCore.ModelBoundReadModel. Time: 2026-03-22T09:12:01.2564726Z. Hash: A0A52F5DA1908A182C6B9EDB3D080F3071D526264E0E3182913E6F14146A7C62
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, QueryValidator } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ModelBoundReadModel } from './ModelBoundReadModel';


export interface GetByIdParameters {
    id: string;
}

export class GetByIdValidator extends QueryValidator<GetByIdParameters> {
    constructor() {
        super();
    }
}

export class GetById extends QueryFor<ModelBoundReadModel, GetByIdParameters> {
    readonly route: string = '/api/asp-net-core/get-by-id';
    readonly validation: QueryValidator = new GetByIdValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ModelBoundReadModel = {} as any;

    constructor() {
        super(ModelBoundReadModel, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', String),
    ];

    id!: string;


    static use(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>] {
        const [result, perform] = useQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
        return [result, perform];
    }

    static useSuspense(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>] {
        const [result, perform] = useSuspenseQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
        return [result, perform];
    }

    static when(condition: boolean): QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters> {
        return new QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters>(GetById, condition);
    }
}
