// @generated by Cratis. Source: AspNetCore.Ticker. Time: 2026-03-22T09:12:01.2621591Z. Hash: 4222FE67A308AC0231F4F5FF433EF2B04D2C9CF924348CEC82EA2752F0460D1D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Ticker } from './Ticker';


export class Observe extends ObservableQueryFor<Ticker> {
    readonly route: string = '/api/asp-net-core/observe';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Ticker = {} as any;

    constructor() {
        super(Ticker, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<Ticker>] {
        const [result] = useObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<Ticker>] {
        const [result] = useSuspenseObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Observe, Ticker> {
        return new ObservableQueryWhen<Observe, Ticker>(Observe, condition);
    }
}
