// @generated by Cratis. Source: TestApps.Features.Ticker.Ticker. Time: 2026-07-19T23:32:51.1097230Z. Hash: 9C9EFEF0232A4460A59A50C4F320A47C9C88745847265C6C6DFEC8F992D760B2
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, QueryValidator } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Ticker } from './Ticker';


export class ObserveValidator extends QueryValidator<object> {
    constructor() {
        super();
    }
}

export class Observe extends ObservableQueryFor<Ticker> {
    readonly route: string = '/api/features/ticker/observe';
    readonly queryName: string = 'TestApps.Features.Ticker.Ticker.Observe';
    readonly validation: QueryValidator = new ObserveValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Ticker = {} as any;

    constructor() {
        super(Ticker, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<Ticker>] {
        const [result] = useObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<Ticker>] {
        const [result] = useSuspenseObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Observe, Ticker> {
        return new ObservableQueryWhen<Observe, Ticker>(Observe, condition);
    }
}
