// @generated by Cratis. Source: AspNetCore.Features.Ticker.Ticker, AspNetCore.Features.Ticker.Ticker. Time: 2026-03-23T07:05:31.7740895Z. Hash: 222F2572F6551654E9B82189A386366EA4FDEF84DEAB9250C85E5D8EF4EC037B
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

export class Observe extends ObservableQueryFor<Ticker> {
    readonly route: string = '/api/features/ticker/observe';
    readonly queryName: string = 'AspNetCore.Features.Ticker.Ticker.Observe';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Ticker = {} as any;

    constructor() {
        super(Ticker, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<Ticker>] {
        const [result] = useObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<Ticker>] {
        const [result] = useSuspenseObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Observe, Ticker> {
        return new ObservableQueryWhen<Observe, Ticker>(Observe, condition);
    }
}

export class Ticker {
    @field(Number)
    count!: number;
    @field(Date)
    lastUpdated!: Date;
}
