// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ObservableCollection.AddObservableCollectionItem. Time: 2026-10-09T18:26:23.2566171Z. Hash: 7CA8AEF12B8E47463E2AEDD15B216AA8EAD1B22EE11220FFBF2ED5DAE4CC3A71
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IAddObservableCollectionItem {
    id?: number;
    label?: string;
}


export class AddObservableCollectionItem extends Command<IAddObservableCollectionItem> implements IAddObservableCollectionItem {
    readonly route: string = '/api/features/observable-collection/add-observable-collection-item';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
        new PropertyDescriptor('label', String, false),
    ];

    #id!: number;
    #label!: string;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this.#id;
    }

    set id(value: number) {
        this.#id = value;
        this.propertyChanged('id');
    }
    get label(): string {
        return this.#label;
    }

    set label(value: string) {
        this.#label = value;
        this.propertyChanged('label');
    }

    static use(initialValues?: IAddObservableCollectionItem): [AddObservableCollectionItem, SetCommandValues<IAddObservableCollectionItem>, ClearCommandValues] {
        return useCommand<AddObservableCollectionItem, IAddObservableCollectionItem>(AddObservableCollectionItem, initialValues);
    }
}
