// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ObservableCollection.RemoveObservableCollectionItem. Time: 2026-10-03T11:14:56.9415300Z. Hash: D66CFEB99B6CA981DB9E4FBE0BCF7D7D8DFDB43DA16B67DF81EE2541E9796244
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IRemoveObservableCollectionItem {
    id?: number;
}


export class RemoveObservableCollectionItem extends Command<IRemoveObservableCollectionItem> implements IRemoveObservableCollectionItem {
    readonly route: string = '/api/features/observable-collection/remove-observable-collection-item';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
    ];

    private _id!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this._id;
    }

    set id(value: number) {
        this._id = value;
        this.propertyChanged('id');
    }

    static use(initialValues?: IRemoveObservableCollectionItem): [RemoveObservableCollectionItem, SetCommandValues<IRemoveObservableCollectionItem>, ClearCommandValues] {
        return useCommand<RemoveObservableCollectionItem, IRemoveObservableCollectionItem>(RemoveObservableCollectionItem, initialValues);
    }
}
