// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Arc.ProxyGenerator.for_GeneratedFileMetadata.when_creating_comment_line;

public class with_hash : Specification
{
    GeneratedFileMetadata _metadata;
    string _commentLine;

    void Establish()
    {
        _metadata = new GeneratedFileMetadata(
            "MyNamespace.MyClass",
            new DateTime(2024, 12, 8, 10, 0, 0, DateTimeKind.Utc),
            "ABC123DEF456");
    }

    void Because() => _commentLine = _metadata.ToCommentLine();

    [Fact] void should_contain_source_type() => _commentLine.ShouldContain("MyNamespace.MyClass");
    [Fact] void should_contain_time() => _commentLine.ShouldContain("2024-12-08T10:00:00");
    [Fact] void should_contain_hash() => _commentLine.ShouldContain("ABC123DEF456");
    [Fact] void should_start_with_marker() => _commentLine.StartsWith("// @generated by Cratis").ShouldBeTrue();
}
