// @generated by Cratis. Source: TestApps.Features.ObservableCollection.AddObservableCollectionItem. Time: 2026-04-28T10:52:51.3717470Z. Hash: D9AC7F9D771FF0CBB2EF467E931FE719DAB960063A1595BA0B4C4A3FA464C9A8
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IAddObservableCollectionItem {
    id?: number;
    label?: string;
}

export class AddObservableCollectionItemValidator extends CommandValidator<IAddObservableCollectionItem> {
    constructor() {
        super();
    }
}

export class AddObservableCollectionItem extends Command<IAddObservableCollectionItem> implements IAddObservableCollectionItem {
    readonly route: string = '/api/features/observable-collection/add-observable-collection-item';
    readonly validation: CommandValidator = new AddObservableCollectionItemValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
        new PropertyDescriptor('label', String, false),
    ];

    private _id!: number;
    private _label!: string;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this._id;
    }

    set id(value: number) {
        this._id = value;
        this.propertyChanged('id');
    }
    get label(): string {
        return this._label;
    }

    set label(value: string) {
        this._label = value;
        this.propertyChanged('label');
    }

    static use(initialValues?: IAddObservableCollectionItem): [AddObservableCollectionItem, SetCommandValues<IAddObservableCollectionItem>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<AddObservableCollectionItem, IAddObservableCollectionItem>(AddObservableCollectionItem, initialValues);
    }
}
