// @generated by Cratis. Source: TestApps.Features.ObservableCollection.ObservableCollectionItem, TestApps.Features.ObservableCollection.ObservableCollectionItem. Time: 2026-07-19T23:32:46.5273810Z. Hash: 6B16AF58B6B9B577C364B80BD85693B9B0EA5E42BFB2F7E0505A33A1DD2708A9
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, QueryValidator, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

class AllSortBy {

    constructor(readonly query: All) {
    }

}

class AllSortByWithoutQuery {

}

export class AllValidator extends QueryValidator<object> {
    constructor() {
        super();
    }
}

export class All extends ObservableQueryFor<ObservableCollectionItem[]> {
    readonly route: string = '/api/features/observable-collection/all';
    readonly queryName: string = 'TestApps.Features.ObservableCollection.ObservableCollectionItem.All';
    readonly validation: QueryValidator = new AllValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ObservableCollectionItem[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(ObservableCollectionItem, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting] {
        return useObservableQuery<ObservableCollectionItem[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ObservableCollectionItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting] {
        return useSuspenseObservableQuery<ObservableCollectionItem[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ObservableCollectionItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: ObservableCollectionItem) => unknown, sorting?: Sorting): ChangeSet<ObservableCollectionItem> {
        return useChangeStream<ObservableCollectionItem, All>(All, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, ObservableCollectionItem[]> {
        return new ObservableQueryWhen<All, ObservableCollectionItem[]>(All, condition);
    }
}

export class ObservableCollectionItem {
    @field(Number)
    id!: number;
    @field(String)
    label!: string;
}
