// @generated by Cratis. Source: TestApps.Features.ObservableCollection.RemoveObservableCollectionItem. Time: 2026-04-28T10:52:51.3717470Z. Hash: 021919845F171A3C27ECA3DC159DD870D8BEECF305400373F3CB03F3DA4963B8
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IRemoveObservableCollectionItem {
    id?: number;
}

export class RemoveObservableCollectionItemValidator extends CommandValidator<IRemoveObservableCollectionItem> {
    constructor() {
        super();
    }
}

export class RemoveObservableCollectionItem extends Command<IRemoveObservableCollectionItem> implements IRemoveObservableCollectionItem {
    readonly route: string = '/api/features/observable-collection/remove-observable-collection-item';
    readonly validation: CommandValidator = new RemoveObservableCollectionItemValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
    ];

    private _id!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this._id;
    }

    set id(value: number) {
        this._id = value;
        this.propertyChanged('id');
    }

    static use(initialValues?: IRemoveObservableCollectionItem): [RemoveObservableCollectionItem, SetCommandValues<IRemoveObservableCollectionItem>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RemoveObservableCollectionItem, IRemoveObservableCollectionItem>(RemoveObservableCollectionItem, initialValues);
    }
}
