// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ObservableCollection.AddObservableCollectionItem. Time: 2026-10-03T11:15:01.4419310Z. Hash: C96C49BEA0D0A219D1586AC1BF2FC72765B38082DB957000BFAFE565582D8320
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IAddObservableCollectionItem {
    id?: number;
    label?: string;
}


export class AddObservableCollectionItem extends Command<IAddObservableCollectionItem> implements IAddObservableCollectionItem {
    readonly route: string = '/api/features/observable-collection/add-observable-collection-item';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
        new PropertyDescriptor('label', String, false),
    ];

    private _id!: number;
    private _label!: string;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this._id;
    }

    set id(value: number) {
        this._id = value;
        this.propertyChanged('id');
    }
    get label(): string {
        return this._label;
    }

    set label(value: string) {
        this._label = value;
        this.propertyChanged('label');
    }

    static use(initialValues?: IAddObservableCollectionItem): [AddObservableCollectionItem, SetCommandValues<IAddObservableCollectionItem>, ClearCommandValues] {
        return useCommand<AddObservableCollectionItem, IAddObservableCollectionItem>(AddObservableCollectionItem, initialValues);
    }
}
