// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ObservableCollection.ObservableCollectionItem. Time: 2026-10-03T11:15:01.4419310Z. Hash: A61B0B0228BD3B9874B3E7DE1F552A306C3E109EF7616BA32C6CFC70BB993DB5
// **DO NOT EDIT** - This file is an automatically generated file.
import { ChangeSet, ObservableQueryFor, Paging, QueryResultWithState, Sorting } from '@cratis/arc/queries';
import { ObservableQueryWhen, SetPage, SetPageSize, SetSorting, useChangeStream, useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ObservableCollectionItem } from './ObservableCollectionItem';

class AllSortBy {

    constructor(readonly query: All) {
    }

}

class AllSortByWithoutQuery {

}


export class All extends ObservableQueryFor<ObservableCollectionItem[]> {
    readonly route: string = '/api/features/observable-collection/all';
    readonly queryName: string = 'Samples.Features.ObservableCollection.ObservableCollectionItem.All';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ObservableCollectionItem[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(ObservableCollectionItem, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting] {
        return useObservableQuery<ObservableCollectionItem[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ObservableCollectionItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting] {
        return useSuspenseObservableQuery<ObservableCollectionItem[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ObservableCollectionItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: ObservableCollectionItem) => unknown, sorting?: Sorting): ChangeSet<ObservableCollectionItem> {
        return useChangeStream<ObservableCollectionItem, All>(All, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, ObservableCollectionItem[]> {
        return new ObservableQueryWhen<All, ObservableCollectionItem[]>(All, condition);
    }
}
