// @generated by Cratis. Source: Samples.Features.ObservableCollection.ObservableCollectionItem. Time: 2026-10-01T10:15:47.5033350Z. Hash: 89297C7AB885E8967986A5A88C3C36208DB2EE3FE91DF630A1B70DAC0A711DB2
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ObservableCollectionItem } from './ObservableCollectionItem';

class AllSortBy {

    constructor(readonly query: All) {
    }

}

class AllSortByWithoutQuery {

}


export class All extends ObservableQueryFor<ObservableCollectionItem[]> {
    readonly route: string = '/api/features/observable-collection/all';
    readonly queryName: string = 'Samples.Features.ObservableCollection.ObservableCollectionItem.All';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ObservableCollectionItem[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(ObservableCollectionItem, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting] {
        return useObservableQuery<ObservableCollectionItem[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ObservableCollectionItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting] {
        return useSuspenseObservableQuery<ObservableCollectionItem[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ObservableCollectionItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ObservableCollectionItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: ObservableCollectionItem) => unknown, sorting?: Sorting): ChangeSet<ObservableCollectionItem> {
        return useChangeStream<ObservableCollectionItem, All>(All, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, ObservableCollectionItem[]> {
        return new ObservableQueryWhen<All, ObservableCollectionItem[]>(All, condition);
    }
}
