// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ObservableCollection.ObservableCollectionItem. Time: 2026-10-03T11:15:01.4419310Z. Hash: 0708E9669F5135514800527E69C240A51D32D2804BC444836C0DD3E30E04E95F
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';

export class ObservableCollectionItem {
    @field(Number)
    id!: number;
    @field(String)
    label!: string;
}
