<?xml version="1.0" encoding="UTF-8" ?>
<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <AssemblyName>EmbeddedConsumer</AssemblyName>
        <RootNamespace>Company.Library</RootNamespace>
        <IsPackable>false</IsPackable>
        <Features>$(Features);embedded-test=forwarded</Features>
        <InterceptorsNamespaces>$(InterceptorsNamespaces);EmbeddedInterceptors.Current</InterceptorsNamespaces>
        <InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);EmbeddedInterceptors.Legacy</InterceptorsPreviewNamespaces>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <CratisEmbeddedScreenplayTaskAssembly>$(MSBuildThisFileDirectory)../../../Tools/Screenplay.Embedded.Build/bin/$(Configuration)/$(TargetFramework)/Cratis.Arc.Screenplay.Embedded.Build.dll</CratisEmbeddedScreenplayTaskAssembly>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../../Arc.Core/Arc.Core.csproj" />
        <ProjectReference Include="../Interceptors.Generator/Interceptors.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <PackageReference Include="Cratis.Chronicle" />
        <ProjectReference Include="../../../Tools/Screenplay.Embedded.Build/Screenplay.Embedded.Build.csproj" ReferenceOutputAssembly="false" />
        <ProjectReference Include="../../../Screenplay.Embedded/Screenplay.Embedded.csproj" />
    </ItemGroup>
    <Import Project="../../../Screenplay.Embedded/build/Cratis.Arc.Screenplay.Embedded.targets" />
</Project>
