// @generated by Cratis. Source: TestApps.Features.ChangeStream.RemoveChangeStreamItem. Time: 2026-07-20T10:41:40.5341110Z. Hash: A31EDE3F1D2ED689918CB6ADCD50AA272FECF9A2ACFA1D1A4CD3808927DAC7E6
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IRemoveChangeStreamItem {
    id?: number;
}


export class RemoveChangeStreamItem extends Command<IRemoveChangeStreamItem> implements IRemoveChangeStreamItem {
    readonly route: string = '/api/features/change-stream/remove-change-stream-item';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
    ];

    private _id!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this._id;
    }

    set id(value: number) {
        this._id = value;
        this.propertyChanged('id');
    }

    static use(initialValues?: IRemoveChangeStreamItem): [RemoveChangeStreamItem, SetCommandValues<IRemoveChangeStreamItem>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RemoveChangeStreamItem, IRemoveChangeStreamItem>(RemoveChangeStreamItem, initialValues);
    }
}
