// @generated by Cratis. Source: TestApps.Features.ChangeStream.UpdateChangeStreamItem. Time: 2026-07-20T10:41:40.5341110Z. Hash: BCBBAFDA71B2CEAE2D0114642C4CDB773F53D84F54B4035CF1745FA7DF9EE8CB
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IUpdateChangeStreamItem {
    id?: number;
    label?: string;
    value?: number;
}


export class UpdateChangeStreamItem extends Command<IUpdateChangeStreamItem> implements IUpdateChangeStreamItem {
    readonly route: string = '/api/features/change-stream/update-change-stream-item';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
        new PropertyDescriptor('label', String, false),
        new PropertyDescriptor('value', Number, false),
    ];

    private _id!: number;
    private _label!: string;
    private _value!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this._id;
    }

    set id(value: number) {
        this._id = value;
        this.propertyChanged('id');
    }
    get label(): string {
        return this._label;
    }

    set label(value: string) {
        this._label = value;
        this.propertyChanged('label');
    }
    get value(): number {
        return this._value;
    }

    set value(value: number) {
        this._value = value;
        this.propertyChanged('value');
    }

    static use(initialValues?: IUpdateChangeStreamItem): [UpdateChangeStreamItem, SetCommandValues<IUpdateChangeStreamItem>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<UpdateChangeStreamItem, IUpdateChangeStreamItem>(UpdateChangeStreamItem, initialValues);
    }
}
