// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.ModelBoundCommand. Time: 2026-10-03T11:14:56.9415300Z. Hash: A5C4539A967EDD628675CBA28FE74AD9CEC62E466D9D70A60E5E10588749CCC7
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IModelBoundCommand {
    stuffToDo?: string;
}


export class ModelBoundCommand extends Command<IModelBoundCommand, string> implements IModelBoundCommand {
    readonly route: string = '/api';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('stuffToDo', String, false),
    ];

    private _stuffToDo!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get stuffToDo(): string {
        return this._stuffToDo;
    }

    set stuffToDo(value: string) {
        this._stuffToDo = value;
        this.propertyChanged('stuffToDo');
    }

    static use(initialValues?: IModelBoundCommand): [ModelBoundCommand, SetCommandValues<IModelBoundCommand>, ClearCommandValues] {
        return useCommand<ModelBoundCommand, IModelBoundCommand, string>(ModelBoundCommand, initialValues);
    }
}
