// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.ModelBoundReadModel, Samples.ModelBoundReadModel, Samples.ModelBoundReadModel. Time: 2026-10-03T11:14:56.9415300Z. Hash: 939563A4CFAC2BA66D34A4AD806A41B1A5F368E2F518D65FA98BEB5841E94FDE
// **DO NOT EDIT** - This file is an automatically generated file.
import { Paging, QueryFor, QueryResultWithState, Sorting } from '@cratis/arc/queries';
import { PerformQuery, QueryWhen, SetPage, SetPageSize, SetSorting, useQuery, useQueryWithPaging, useSuspenseQuery, useSuspenseQueryWithPaging } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

export interface GetByIdParameters {
    id: string;
}


export class GetById extends QueryFor<ModelBoundReadModel, GetByIdParameters> {
    readonly route: string = '/api/get-by-id';
    readonly queryName: string = 'Samples.ModelBoundReadModel.GetById';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ModelBoundReadModel = {} as ModelBoundReadModel;

    constructor() {
        super(ModelBoundReadModel, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', String, false),
    ];

    id!: string;


    static use(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>, SetSorting] {
        return useQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
    }

    static useSuspense(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>, SetSorting] {
        return useSuspenseQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
    }

    static when(condition: boolean): QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters> {
        return new QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters>(GetById, condition);
    }
}

class GetAllSortBy {

    constructor(readonly query: GetAll) {
    }

}

class GetAllSortByWithoutQuery {

}


export class GetAll extends QueryFor<ModelBoundReadModel[]> {
    readonly route: string = '/api/get-all';
    readonly queryName: string = 'Samples.ModelBoundReadModel.GetAll';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ModelBoundReadModel[] = [];
    private readonly _sortBy: GetAllSortBy;
    private static readonly _sortBy: GetAllSortByWithoutQuery = new GetAllSortByWithoutQuery();

    constructor() {
        super(ModelBoundReadModel, true);
        this._sortBy = new GetAllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): GetAllSortBy {
        return this._sortBy;
    }

    static get sortBy(): GetAllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting] {
        return useQuery<ModelBoundReadModel[], GetAll>(GetAll, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<ModelBoundReadModel[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting] {
        return useSuspenseQuery<ModelBoundReadModel[], GetAll>(GetAll, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<ModelBoundReadModel[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): QueryWhen<GetAll, ModelBoundReadModel[]> {
        return new QueryWhen<GetAll, ModelBoundReadModel[]>(GetAll, condition);
    }
}

export class ModelBoundReadModel {
    @field(Number)
    data!: number;
}
