// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Cratis.Arc.Queries.QuerySubscriptionMetadata. Time: 2026-10-03T11:14:56.9415300Z. Hash: 503293AA40D2EBDDFC1F7B4DBC6B8F8E53E83F5DA06F4F2A1F07D0768AF0B6E7
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';
import { QuerySubscriptionClientInfo } from './QuerySubscriptionClientInfo';

/**
 * Represents metadata for a single query subscription.
 */
export class QuerySubscriptionMetadata {

    /**
     * Gets the unique identifier for this subscription (client-generated queryId).
     */
    @field(String)
    subscriptionId!: string;

    /**
     * Gets the query identifier (fully qualified query name).
     */
    @field(String)
    queryIdentifier!: string;

    /**
     * Gets the read model type.
     */
    @field(String)
    readModelType!: string;

    /**
     * Gets when the subscription was first connected.
     */
    @field(Date)
    connectedAt!: Date;

    /**
     * Gets the client information (headers, user agent, etc.).
     */
    @field(QuerySubscriptionClientInfo)
    clientInfo!: QuerySubscriptionClientInfo;

    /**
     * Gets the last time a ping was sent to the client.
     */
    @field(Date)
    lastPingSentAt?: Date;

    /**
     * Gets the last time a pong was received from the client.
     */
    @field(Date)
    lastPongReceivedAt?: Date;

    /**
     * Gets the last time data was served to the client.
     */
    @field(Date)
    lastDataServedAt?: Date;
}
