// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Cratis.Arc.ProxyGenerator.Templates;

namespace Cratis.Arc.ProxyGenerator.for_DescriptorExtensions;

public class when_flushing_pending_content : Specification
{
    string _directory = null!;
    string _path = null!;
    string _content = null!;
    string _firstOutput = null!;
    DateTime _firstTimestamp;
    GeneratedFileMetadata _firstMetadata = null!;
    Dictionary<string, GeneratedFileMetadata> _files = [];

    async Task Establish()
    {
        _directory = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        Directory.CreateDirectory(_directory);
        _path = Path.Combine(_directory, "Sample.ts");
        _content = TemplateTypes.Type(new { Name = "Sample", Properties = Array.Empty<object>(), Imports = Array.Empty<object>() });
        await File.WriteAllTextAsync(_path, "// @generated by Cratis. Source: Sample. Time: 2020-01-01T00:00:00Z\n/* eslint-disable no-empty-interface */\nexport class Sample {}");
    }

    async Task Because()
    {
        var pending = new Dictionary<string, (string Content, string SourceTypeName)> { [_path] = (_content, "Sample") };
        await DescriptorExtensions.FlushPendingContent(pending, _files, _ => { });
        _firstOutput = await File.ReadAllTextAsync(_path);
        _firstTimestamp = File.GetLastWriteTimeUtc(_path);
        _firstMetadata = _files[_path];
        await DescriptorExtensions.FlushPendingContent(pending, _files, _ => { });
    }

    [Fact] void should_migrate_the_legacy_marker_to_after_the_license() => File.ReadAllLines(_path)[3].ShouldEqual(_firstMetadata.ToCommentLine());
    [Fact] void should_preserve_the_payload_hash() => _files[_path].ContentHash.ShouldEqual(GeneratedFileMetadata.ComputeHash(_content));
    [Fact] void should_not_rewrite_identical_new_output() => File.ReadAllText(_path).ShouldEqual(_firstOutput);
    [Fact] void should_preserve_the_filesystem_timestamp() => File.GetLastWriteTimeUtc(_path).ShouldEqual(_firstTimestamp);
    [Fact] void should_preserve_the_generation_timestamp() => _files[_path].GeneratedTime.ToUniversalTime().ShouldEqual(_firstMetadata.GeneratedTime.ToUniversalTime());
    [Fact] void should_report_the_second_write_as_unchanged() => _files[_path].WasWritten.ShouldBeFalse();
    [Fact] void should_recognize_the_new_marker() => GeneratedFileMetadata.IsGeneratedFile(_path, out _).ShouldBeTrue();

    void Destroy() => Directory.Delete(_directory, true);
}
