// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ChangeStream.RemoveChangeStreamItem. Time: 2026-10-08T15:49:51.1371288Z. Hash: 605C90A2ADFFC777362200F81A63E8133272CC195F1461AB1C92FF20738F7458
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IRemoveChangeStreamItem {
    id?: number;
}


export class RemoveChangeStreamItem extends Command<IRemoveChangeStreamItem> implements IRemoveChangeStreamItem {
    readonly route: string = '/api/features/change-stream/remove-change-stream-item';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
    ];

    #id!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this.#id;
    }

    set id(value: number) {
        this.#id = value;
        this.propertyChanged('id');
    }

    static use(initialValues?: IRemoveChangeStreamItem): [RemoveChangeStreamItem, SetCommandValues<IRemoveChangeStreamItem>, ClearCommandValues] {
        return useCommand<RemoveChangeStreamItem, IRemoveChangeStreamItem>(RemoveChangeStreamItem, initialValues);
    }
}
