// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ChangeStream.UpdateChangeStreamItem. Time: 2026-10-08T15:49:51.1371288Z. Hash: FDD637EB872014DA43CE7D28CD045FDC8C13774F13FAFEC2FD0D887B9FF4D10A
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IUpdateChangeStreamItem {
    id?: number;
    label?: string;
    value?: number;
}


export class UpdateChangeStreamItem extends Command<IUpdateChangeStreamItem> implements IUpdateChangeStreamItem {
    readonly route: string = '/api/features/change-stream/update-change-stream-item';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Number, false),
        new PropertyDescriptor('label', String, false),
        new PropertyDescriptor('value', Number, false),
    ];

    #id!: number;
    #label!: string;
    #value!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): number {
        return this.#id;
    }

    set id(value: number) {
        this.#id = value;
        this.propertyChanged('id');
    }
    get label(): string {
        return this.#label;
    }

    set label(value: string) {
        this.#label = value;
        this.propertyChanged('label');
    }
    get value(): number {
        return this.#value;
    }

    set value(value: number) {
        this.#value = value;
        this.propertyChanged('value');
    }

    static use(initialValues?: IUpdateChangeStreamItem): [UpdateChangeStreamItem, SetCommandValues<IUpdateChangeStreamItem>, ClearCommandValues] {
        return useCommand<UpdateChangeStreamItem, IUpdateChangeStreamItem>(UpdateChangeStreamItem, initialValues);
    }
}
