// @generated by Cratis. Source: TestApps.Features.QueryShowcase.ShowcaseItem. Time: 2026-03-26T10:40:07.6866700Z. Hash: A0EC78B6EA04D4A47B44D4E619389125467AD1AE00FC0588D99433E9F951C349
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShowcaseItem } from './ShowcaseItem';

class AllSortBy {

    constructor(readonly query: All) {
    }

}

class AllSortByWithoutQuery {

}

export class All extends ObservableQueryFor<ShowcaseItem[]> {
    readonly route: string = '/api/features/query-showcase/all';
    readonly queryName: string = 'TestApps.Features.QueryShowcase.ShowcaseItem.All';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(ShowcaseItem, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting] {
        return useObservableQuery<ShowcaseItem[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ShowcaseItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting] {
        return useSuspenseObservableQuery<ShowcaseItem[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ShowcaseItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, ShowcaseItem[]> {
        return new ObservableQueryWhen<All, ShowcaseItem[]>(All, condition);
    }
}
