// @generated by Cratis. Source: TestApps.Features.QueryShowcase.ShowcaseItem. Time: 2026-09-06T08:22:30.3863580Z. Hash: E428E1D055ADF89095CD7E5ACCD7CB0E54013AF61CEFB8854C14A579011AEAD6
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShowcaseItem } from './ShowcaseItem';


export interface ByIdParameters {
    id: number;
}


export class ById extends QueryFor<ShowcaseItem, ByIdParameters> {
    readonly route: string = '/api/features/query-showcase/by-id';
    readonly queryName: string = 'TestApps.Features.QueryShowcase.ShowcaseItem.ById';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem = {} as ShowcaseItem;

    constructor() {
        super(ShowcaseItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', Number, false),
    ];

    id!: number;


    static use(args?: ByIdParameters): [QueryResultWithState<ShowcaseItem>, PerformQuery<ByIdParameters>, SetSorting] {
        return useQuery<ShowcaseItem, ById, ByIdParameters>(ById, args);
    }

    static useSuspense(args?: ByIdParameters): [QueryResultWithState<ShowcaseItem>, PerformQuery<ByIdParameters>, SetSorting] {
        return useSuspenseQuery<ShowcaseItem, ById, ByIdParameters>(ById, args);
    }

    static when(condition: boolean): QueryWhen<ById, ShowcaseItem, ByIdParameters> {
        return new QueryWhen<ById, ShowcaseItem, ByIdParameters>(ById, condition);
    }
}
