// @generated by Cratis. Source: TestApps.Features.QueryShowcase.ShowcaseItem. Time: 2026-05-06T11:10:29.7191050Z. Hash: 296B090352FA64EA8650AD338D15089DF667E325601EFFE42BA0EEDCA86492C9
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, QueryValidator } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShowcaseItem } from './ShowcaseItem';


export interface ByIdParameters {
    id: number;
}

export class ByIdValidator extends QueryValidator<ByIdParameters> {
    constructor() {
        super();
    }
}

export class ById extends QueryFor<ShowcaseItem, ByIdParameters> {
    readonly route: string = '/api/features/query-showcase/by-id';
    readonly queryName: string = 'TestApps.Features.QueryShowcase.ShowcaseItem.ById';
    readonly validation: QueryValidator = new ByIdValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem = {} as any;

    constructor() {
        super(ShowcaseItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', Number, false),
    ];

    id!: number;


    static use(args?: ByIdParameters): [QueryResultWithState<ShowcaseItem>, PerformQuery<ByIdParameters>, SetSorting] {
        return useQuery<ShowcaseItem, ById, ByIdParameters>(ById, args);
    }

    static useSuspense(args?: ByIdParameters): [QueryResultWithState<ShowcaseItem>, PerformQuery<ByIdParameters>, SetSorting] {
        return useSuspenseQuery<ShowcaseItem, ById, ByIdParameters>(ById, args);
    }

    static when(condition: boolean): QueryWhen<ById, ShowcaseItem, ByIdParameters> {
        return new QueryWhen<ById, ShowcaseItem, ByIdParameters>(ById, condition);
    }
}
