// @generated by Cratis. Source: TestApps.Features.QueryShowcase.ShowcaseItem. Time: 2026-03-27T13:34:11.7475140Z. Hash: 409EB64C1540394FB5C92ECAF59F1EA0F523013ADDCFA981DBF91AE186806E01
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, QueryValidator } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShowcaseItem } from './ShowcaseItem';


export interface ByIdParameters {
    id: number;
}

export class ByIdValidator extends QueryValidator<ByIdParameters> {
    constructor() {
        super();
    }
}

export class ById extends QueryFor<ShowcaseItem, ByIdParameters> {
    readonly route: string = '/api/features/query-showcase/by-id';
    readonly validation: QueryValidator = new ByIdValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem = {} as any;

    constructor() {
        super(ShowcaseItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', Number, false),
    ];

    id!: number;


    static use(args?: ByIdParameters): [QueryResultWithState<ShowcaseItem>, PerformQuery<ByIdParameters>] {
        const [result, perform] = useQuery<ShowcaseItem, ById, ByIdParameters>(ById, args);
        return [result, perform];
    }

    static useSuspense(args?: ByIdParameters): [QueryResultWithState<ShowcaseItem>, PerformQuery<ByIdParameters>] {
        const [result, perform] = useSuspenseQuery<ShowcaseItem, ById, ByIdParameters>(ById, args);
        return [result, perform];
    }

    static when(condition: boolean): QueryWhen<ById, ShowcaseItem, ByIdParameters> {
        return new QueryWhen<ById, ShowcaseItem, ByIdParameters>(ById, condition);
    }
}
