// @generated by Cratis. Source: TestApps.Features.QueryShowcase.ShowcaseItem. Time: 2026-03-26T10:40:07.6866700Z. Hash: 1FE89F0F386E3BABCD0110E01FBD8FDDA29714E4B59416C3133E2E20C82EB2A5
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShowcaseItem } from './ShowcaseItem';


export class Latest extends ObservableQueryFor<ShowcaseItem> {
    readonly route: string = '/api/features/query-showcase/latest';
    readonly queryName: string = 'TestApps.Features.QueryShowcase.ShowcaseItem.Latest';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem = {} as any;

    constructor() {
        super(ShowcaseItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<ShowcaseItem>] {
        const [result] = useObservableQuery<ShowcaseItem, Latest>(Latest);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<ShowcaseItem>] {
        const [result] = useSuspenseObservableQuery<ShowcaseItem, Latest>(Latest);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Latest, ShowcaseItem> {
        return new ObservableQueryWhen<Latest, ShowcaseItem>(Latest, condition);
    }
}
