// @generated by Cratis. Source: TestApps.Features.QueryShowcase.ShowcaseItem. Time: 2026-07-19T23:32:51.1097230Z. Hash: FDB4F3B85B09D643C660A61724614A0269AD830646FFF1F81AB10E03F4085548
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, QueryValidator } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShowcaseItem } from './ShowcaseItem';


export class LatestValidator extends QueryValidator<object> {
    constructor() {
        super();
    }
}

export class Latest extends ObservableQueryFor<ShowcaseItem> {
    readonly route: string = '/api/features/query-showcase/latest';
    readonly queryName: string = 'TestApps.Features.QueryShowcase.ShowcaseItem.Latest';
    readonly validation: QueryValidator = new LatestValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem = {} as any;

    constructor() {
        super(ShowcaseItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<ShowcaseItem>] {
        const [result] = useObservableQuery<ShowcaseItem, Latest>(Latest);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<ShowcaseItem>] {
        const [result] = useSuspenseObservableQuery<ShowcaseItem, Latest>(Latest);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Latest, ShowcaseItem> {
        return new ObservableQueryWhen<Latest, ShowcaseItem>(Latest, condition);
    }
}
