// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Arc.ProxyGenerator.for_IndexFileManager.when_updating_index_file;

public class with_manual_export_to_a_package : Specification
{
    string _tempDir;
    List<string> _messages;
    string _indexPath;
    bool _result;

    void Establish()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        Directory.CreateDirectory(_tempDir);

        // Generated .ts file (content unchanged, so WasWritten = false)
        File.WriteAllText(Path.Combine(_tempDir, "RegisterFacility.ts"), "// @generated by Cratis. Source: RegisterFacility. Time: 2025-01-01T00:00:00.0000000Z. Hash: ABC\nexport class RegisterFacility {}");

        // A hand-added re-export of an entire package — a non-relative specifier the generator
        // never wrote and can never resolve on disk.
        _indexPath = Path.Combine(_tempDir, "index.ts");
        File.WriteAllText(_indexPath, "export * from './RegisterFacility';\nexport * from '@cratis/components';\n");

        _messages = [];
    }

    void Because()
    {
        var dict = new Dictionary<string, GeneratedFileMetadata>
        {
            [Path.Combine(_tempDir, "RegisterFacility.ts")] = new GeneratedFileMetadata("RegisterFacility", DateTime.UtcNow, GeneratedFileMetadata.ComputeHash(""), false),
        };

        _result = IndexFileManager.UpdateIndexFile(_tempDir, dict, [], _messages.Add, _tempDir);
    }

    [Fact] void should_not_rewrite_index() => _result.ShouldBeFalse();
    [Fact] void should_preserve_package_export() => File.ReadAllText(_indexPath).ShouldContain("export * from '@cratis/components';");
    [Fact] void should_preserve_generated_export() => File.ReadAllText(_indexPath).ShouldContain("export * from './RegisterFacility';");

    void Cleanup()
    {
        if (Directory.Exists(_tempDir))
        {
            Directory.Delete(_tempDir, true);
        }
    }
}
