// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Arc.ProxyGenerator.for_IndexFileManager.when_updating_index_file;

public class with_manual_export_to_a_sibling_folder_alongside_a_new_generated_file : Specification
{
    string _tempDir;
    List<string> _messages;
    string _indexPath;
    bool _firstResult;
    bool _secondResult;

    void Establish()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        Directory.CreateDirectory(_tempDir);

        // Existing generated .ts file (content unchanged, so WasWritten = false)
        File.WriteAllText(Path.Combine(_tempDir, "RegisterFacility.ts"), "// @generated by Cratis. Source: RegisterFacility. Time: 2025-01-01T00:00:00.0000000Z. Hash: ABC\nexport class RegisterFacility {}");

        // A newly generated .ts file that was written this run, forcing a rewrite of the index.
        File.WriteAllText(Path.Combine(_tempDir, "CreateFacility.ts"), "// @generated by Cratis. Source: CreateFacility. Time: 2025-01-01T00:00:00.0000000Z. Hash: DEF\nexport class CreateFacility {}");

        // Hand-written sibling folder with its own barrel — the generator has never written a folder export.
        var listDir = Path.Combine(_tempDir, "List");
        Directory.CreateDirectory(listDir);
        File.WriteAllText(Path.Combine(listDir, "index.ts"), "export * from './FacilityList';\n");

        // Existing index.ts only knows about RegisterFacility and the sibling folder.
        _indexPath = Path.Combine(_tempDir, "index.ts");
        File.WriteAllText(_indexPath, "export * from './RegisterFacility';\nexport * from './List';\n");

        _messages = [];
    }

    void Because()
    {
        var dict = new Dictionary<string, GeneratedFileMetadata>
        {
            [Path.Combine(_tempDir, "RegisterFacility.ts")] = new GeneratedFileMetadata("RegisterFacility", DateTime.UtcNow, GeneratedFileMetadata.ComputeHash(""), false),
            [Path.Combine(_tempDir, "CreateFacility.ts")] = new GeneratedFileMetadata("CreateFacility", DateTime.UtcNow, GeneratedFileMetadata.ComputeHash(""), true),
        };

        _firstResult = IndexFileManager.UpdateIndexFile(_tempDir, dict, [], _messages.Add, _tempDir);

        // A second run against the now-rewritten file must be a no-op.
        _secondResult = IndexFileManager.UpdateIndexFile(_tempDir, dict, [], _messages.Add, _tempDir);
    }

    [Fact] void should_rewrite_index_on_first_run() => _firstResult.ShouldBeTrue();
    [Fact] void should_not_rewrite_index_on_second_run() => _secondResult.ShouldBeFalse();
    [Fact] void should_add_new_generated_export() => File.ReadAllText(_indexPath).ShouldContain("export * from './CreateFacility';");
    [Fact] void should_preserve_existing_generated_export() => File.ReadAllText(_indexPath).ShouldContain("export * from './RegisterFacility';");
    [Fact] void should_preserve_folder_export() => File.ReadAllText(_indexPath).ShouldContain("export * from './List';");

    void Cleanup()
    {
        if (Directory.Exists(_tempDir))
        {
            Directory.Delete(_tempDir, true);
        }
    }
}
