// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Arc.ProxyGenerator.for_IndexFileManager.when_updating_index_file;

public class with_manual_tsx_export_alongside_generated_file : Specification
{
    string _tempDir;
    List<string> _messages;
    string _indexPath;

    void Establish()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        Directory.CreateDirectory(_tempDir);

        // Generated .ts file
        File.WriteAllText(Path.Combine(_tempDir, "RegisterFacility.ts"), "// @generated by Cratis. Source: RegisterFacility. Time: 2025-01-01T00:00:00.0000000Z. Hash: ABC\nexport class RegisterFacility {}");

        // Hand-written .tsx component (not generated)
        File.WriteAllText(Path.Combine(_tempDir, "AddFacilityDialog.tsx"), "export const AddFacilityDialog = () => <div />;");

        // Existing index.ts with both exports
        _indexPath = Path.Combine(_tempDir, "index.ts");
        File.WriteAllText(_indexPath, "export * from './RegisterFacility';\nexport * from './AddFacilityDialog';\n");

        _messages = [];
    }

    void Because()
    {
        var dict = new Dictionary<string, GeneratedFileMetadata>
        {
            [Path.Combine(_tempDir, "RegisterFacility.ts")] = new GeneratedFileMetadata("RegisterFacility", DateTime.UtcNow, GeneratedFileMetadata.ComputeHash(""), true),
        };

        IndexFileManager.UpdateIndexFile(_tempDir, dict, [], _messages.Add, _tempDir);
    }

    [Fact] void should_preserve_manual_tsx_export() => File.ReadAllText(_indexPath).ShouldContain("export * from './AddFacilityDialog';");
    [Fact] void should_keep_generated_export() => File.ReadAllText(_indexPath).ShouldContain("export * from './RegisterFacility';");

    void Cleanup()
    {
        if (Directory.Exists(_tempDir))
        {
            Directory.Delete(_tempDir, true);
        }
    }
}
