// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Arc.ProxyGenerator.for_IndexFileManager.when_updating_index_file;

public class with_export_to_a_sibling_folder_without_a_barrel : Specification
{
    string _tempDir;
    List<string> _messages;
    string _indexPath;
    bool _result;

    void Establish()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        Directory.CreateDirectory(_tempDir);

        // Generated .ts file (content unchanged, so WasWritten = false)
        File.WriteAllText(Path.Combine(_tempDir, "RegisterFacility.ts"), "// @generated by Cratis. Source: RegisterFacility. Time: 2025-01-01T00:00:00.0000000Z. Hash: ABC\nexport class RegisterFacility {}");

        // The "Assets" directory exists but has no index.ts/index.tsx barrel — it does not genuinely
        // resolve as a module, so the export to it is a deliberate pruning boundary, not preserved.
        var assetsDir = Path.Combine(_tempDir, "Assets");
        Directory.CreateDirectory(assetsDir);
        File.WriteAllText(Path.Combine(assetsDir, "logo.png"), "not-a-barrel");

        _indexPath = Path.Combine(_tempDir, "index.ts");
        File.WriteAllText(_indexPath, "export * from './RegisterFacility';\nexport * from './Assets';\n");

        _messages = [];
    }

    void Because()
    {
        var dict = new Dictionary<string, GeneratedFileMetadata>
        {
            [Path.Combine(_tempDir, "RegisterFacility.ts")] = new GeneratedFileMetadata("RegisterFacility", DateTime.UtcNow, GeneratedFileMetadata.ComputeHash(""), false),
        };

        _result = IndexFileManager.UpdateIndexFile(_tempDir, dict, [], _messages.Add, _tempDir);
    }

    [Fact] void should_rewrite_index() => _result.ShouldBeTrue();
    [Fact] void should_prune_export_to_folder_without_a_barrel() => File.ReadAllText(_indexPath).ShouldNotContain("export * from './Assets';");
    [Fact] void should_keep_generated_export() => File.ReadAllText(_indexPath).ShouldContain("export * from './RegisterFacility';");

    void Cleanup()
    {
        if (Directory.Exists(_tempDir))
        {
            Directory.Delete(_tempDir, true);
        }
    }
}
