// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

import { useState } from 'react';
import { ById, GetAll, Latest, All } from '../QueryShowcase/ShowcaseItem';

/**
 * Page demonstrating conditional queries via the `when()` static helper.
 *
 * Every query class generated by the proxy generator exposes a `when(condition)` factory
 * that returns a `QueryWhen` / `ObservableQueryWhen` wrapper. Calling `.use()` on the
 * wrapper behaves identically to calling the plain `.use()` hook when `condition` is
 * `true`, and is a no-op that returns an empty result when `condition` is `false`.
 *
 * This prevents spurious network requests and SSE subscriptions from being opened
 * before the necessary data (e.g. a selected id) is available.
 */
export const ConditionalQueriesPage = () => {
    const [byIdEnabled, setByIdEnabled] = useState(false);
    const [selectedId, setSelectedId] = useState(1);
    const [getAllEnabled, setGetAllEnabled] = useState(false);
    const [latestEnabled, setLatestEnabled] = useState(false);
    const [allEnabled, setAllEnabled] = useState(false);

    return (
        <div>
            <h2>Conditional Queries</h2>
            <p>
                Each section has an <strong>Enable</strong> toggle. When disabled the query or
                subscription is <em>never started</em> — no HTTP request is made, no SSE connection
                opened. Toggle it on to activate, and off again to stop.
            </p>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 }}>

                <Section title="Regular — single (ById.when)">
                    <p style={{ fontSize: 13, color: '#555' }}>
                        <code>ById.when(enabled).use(&#123; id &#125;)</code> — fetches one item
                        only when both <em>enabled</em> and an <em>id</em> are provided.
                    </p>
                    <Controls>
                        <label>
                            id:{' '}
                            <input
                                type="number"
                                value={selectedId}
                                min={1}
                                onChange={e => setSelectedId(Number(e.target.value))}
                                style={{ width: 60, marginLeft: 4 }}
                            />
                        </label>
                        <Toggle label="Enable" enabled={byIdEnabled} onChange={setByIdEnabled} />
                    </Controls>
                    <Status enabled={byIdEnabled} />
                    <ByIdConditional id={selectedId} enabled={byIdEnabled} />
                </Section>

                <Section title="Regular — collection (GetAll.when)">
                    <p style={{ fontSize: 13, color: '#555' }}>
                        <code>GetAll.when(enabled).use()</code> — fetches the static collection
                        only when enabled.
                    </p>
                    <Controls>
                        <Toggle label="Enable" enabled={getAllEnabled} onChange={setGetAllEnabled} />
                    </Controls>
                    <Status enabled={getAllEnabled} />
                    <GetAllConditional enabled={getAllEnabled} />
                </Section>

                <Section title="Observable — single (Latest.when)">
                    <p style={{ fontSize: 13, color: '#555' }}>
                        <code>Latest.when(enabled).use()</code> — opens an SSE subscription to
                        the live single-item stream only when enabled. Updates every 3 s.
                    </p>
                    <Controls>
                        <Toggle label="Enable" enabled={latestEnabled} onChange={setLatestEnabled} />
                    </Controls>
                    <Status enabled={latestEnabled} />
                    <LatestConditional enabled={latestEnabled} />
                </Section>

                <Section title="Observable — collection (All.when)">
                    <p style={{ fontSize: 13, color: '#555' }}>
                        <code>All.when(enabled).use()</code> — opens an SSE subscription to the
                        live collection stream only when enabled. Updates every 3 s.
                    </p>
                    <Controls>
                        <Toggle label="Enable" enabled={allEnabled} onChange={setAllEnabled} />
                    </Controls>
                    <Status enabled={allEnabled} />
                    <AllConditional enabled={allEnabled} />
                </Section>

            </div>
        </div>
    );
};

// ----- sub-components --------------------------------------------------------

interface ByIdConditionalProps {
    id: number;
    enabled: boolean;
}

const ByIdConditional = ({ id, enabled }: ByIdConditionalProps) => {
    const [result] = ById.when(enabled).use({ id });

    if (!enabled || !result.hasData) return <Empty />;
    if (result.isPerforming) return <p>Loading…</p>;

    const item = result.data;
    return <ItemCard id={item.id} name={item.name} updatedAt={item.updatedAt} />;
};

interface GetAllConditionalProps {
    enabled: boolean;
}

const GetAllConditional = ({ enabled }: GetAllConditionalProps) => {
    const [result] = GetAll.when(enabled).use();

    if (!enabled || !result.hasData) return <Empty />;
    if (result.isPerforming) return <p>Loading…</p>;

    return (
        <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
            {(result.data ?? []).map(item => (
                <li key={item.id} style={{ borderBottom: '1px solid #eee', padding: '4px 0' }}>
                    <ItemCard id={item.id} name={item.name} updatedAt={item.updatedAt} />
                </li>
            ))}
        </ul>
    );
};

interface LatestConditionalProps {
    enabled: boolean;
}

const LatestConditional = ({ enabled }: LatestConditionalProps) => {
    const [result] = Latest.when(enabled).use();

    if (!enabled || !result.hasData) return <Empty />;
    if (result.isPerforming) return <p>Connecting…</p>;

    const item = result.data;
    return <ItemCard id={item.id} name={item.name} updatedAt={item.updatedAt} />;
};

interface AllConditionalProps {
    enabled: boolean;
}

const AllConditional = ({ enabled }: AllConditionalProps) => {
    const [result] = All.when(enabled).use();

    if (!enabled || !result.hasData) return <Empty />;
    if (result.isPerforming) return <p>Connecting…</p>;

    return (
        <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
            {(result.data ?? []).map(item => (
                <li key={item.id} style={{ borderBottom: '1px solid #eee', padding: '4px 0' }}>
                    <ItemCard id={item.id} name={item.name} updatedAt={item.updatedAt} />
                </li>
            ))}
        </ul>
    );
};

// ----- shared primitives ----------------------------------------------------

interface SectionProps {
    title: string;
    children: React.ReactNode;
}

const Section = ({ title, children }: SectionProps) => (
    <div style={{ border: '1px solid #ddd', borderRadius: 6, padding: 16 }}>
        <h3 style={{ margin: '0 0 12px', fontSize: 15 }}>{title}</h3>
        {children}
    </div>
);

interface ControlsProps {
    children: React.ReactNode;
}

const Controls = ({ children }: ControlsProps) => (
    <div style={{ display: 'flex', gap: 16, alignItems: 'center', marginBottom: 12 }}>
        {children}
    </div>
);

interface ToggleProps {
    label: string;
    enabled: boolean;
    onChange: (next: boolean) => void;
}

const Toggle = ({ label, enabled, onChange }: ToggleProps) => (
    <label style={{ display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer', userSelect: 'none' }}>
        <input
            type="checkbox"
            checked={enabled}
            onChange={e => onChange(e.target.checked)}
        />
        {label}
    </label>
);

interface StatusProps {
    enabled: boolean;
}

const Status = ({ enabled }: StatusProps) => (
    <div style={{
        fontSize: 12,
        marginBottom: 8,
        color: enabled ? '#2a7c2a' : '#999',
        fontStyle: 'italic',
    }}>
        {enabled ? '● active — query / subscription running' : '○ inactive — no request sent'}
    </div>
);

const Empty = () => (
    <p style={{ color: '#aaa', fontStyle: 'italic', margin: 0 }}>Nothing to show — query is disabled.</p>
);

interface ItemCardProps {
    id: number;
    name: string;
    updatedAt: Date;
}

const ItemCard = ({ id, name, updatedAt }: ItemCardProps) => (
    <div>
        <span style={{ color: '#888', fontSize: 11, marginRight: 6 }}>#{id}</span>
        <strong>{name}</strong>
        <span style={{ color: '#aaa', fontSize: 11, marginLeft: 8 }}>
            {new Date(updatedAt).toLocaleTimeString()}
        </span>
    </div>
);
