// @generated by Cratis. Source: TestApps.Features.LiveFeed.PostToFeed. Time: 2026-07-20T10:41:40.5341110Z. Hash: DEE347DDDEFAB2D7D43AB133BC992BAC5F4D0B21DB2FAD7F454B6E7AD5A325C2
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { LiveFeedMessage } from './LiveFeedMessage';

export interface IPostToFeed {
    author?: string;
    text?: string;
}


export class PostToFeed extends Command<IPostToFeed, LiveFeedMessage> implements IPostToFeed {
    readonly route: string = '/api/features/live-feed';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('author', String, false),
        new PropertyDescriptor('text', String, false),
    ];

    private _author!: string;
    private _text!: string;

    constructor() {
        super(LiveFeedMessage, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get author(): string {
        return this._author;
    }

    set author(value: string) {
        this._author = value;
        this.propertyChanged('author');
    }
    get text(): string {
        return this._text;
    }

    set text(value: string) {
        this._text = value;
        this.propertyChanged('text');
    }

    static use(initialValues?: IPostToFeed): [PostToFeed, SetCommandValues<IPostToFeed>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<PostToFeed, IPostToFeed>(PostToFeed, initialValues);
    }
}
