// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Cratis.Arc.Queries.QueryHealth. Time: 2026-10-03T11:15:01.4419310Z. Hash: 61C6AF8F0B1B6B6395F7C8D8548D00C6001B637A63BFA547AC22883601F42E9C
// **DO NOT EDIT** - This file is an automatically generated file.
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { ObservableQueryWhen, useObservableQuery, useSuspenseObservableQuery } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { QueryHealth } from './QueryHealth';



/**
 * Observes query health as a real-time stream.
 */
export class ObserveHealth extends ObservableQueryFor<QueryHealth> {
    readonly route: string = '/.cratis/queries/health';
    readonly queryName: string = 'Cratis.Arc.Queries.QueryHealth.ObserveHealth';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: QueryHealth = {} as QueryHealth;

    constructor() {
        super(QueryHealth, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<QueryHealth>] {
        const [result] = useObservableQuery<QueryHealth, ObserveHealth>(ObserveHealth);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<QueryHealth>] {
        const [result] = useSuspenseObservableQuery<QueryHealth, ObserveHealth>(ObserveHealth);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<ObserveHealth, QueryHealth> {
        return new ObservableQueryWhen<ObserveHealth, QueryHealth>(ObserveHealth, condition);
    }
}
