// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Cratis.Arc.Queries.QuerySubscriptionAggregate. Time: 2026-10-03T11:15:01.4419310Z. Hash: 6581598784A19970517DC5DC9E79486D1D63CF99907F12CDA8D62B1D51D69990
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';
import { QuerySubscriber } from './QuerySubscriber';

/**
 * Represents a query-centric view of all active subscriptions for a single query.
 */
export class QuerySubscriptionAggregate {

    /**
     * Gets the fully qualified query name (e.g. `MyApp.Authors.Listing.AllAuthors`). Matches the `queryName` property on the generated TypeScript proxy.
     */
    @field(String)
    queryName!: string;

    /**
     * Gets the total number of active subscribers for this query.
     */
    @field(Number)
    totalSubscriptions!: number;

    /**
     * Gets all active subscribers for this query, one entry per physical connection/subscription pair.
     */
    @field(QuerySubscriber, true)
    subscribers!: QuerySubscriber[];
}
