// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Cratis.Arc.Queries.QuerySubscriptionClientInfo. Time: 2026-10-03T11:15:01.4419310Z. Hash: 830836FC514CE0FCBE373958B6CFADE5ADA4AE2CB7986A6644144F6EC575E566
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';

/**
 * Represents client information for a query subscription.
 */
export class QuerySubscriptionClientInfo {

    /**
     * Gets the remote IP address.
     */
    @field(String)
    remoteIpAddress?: string;

    /**
     * Gets the user agent string.
     */
    @field(String)
    userAgent?: string;

    /**
     * Gets the user identity (if authenticated).
     */
    @field(String)
    userId?: string;

    /**
     * Gets the connection protocol (WebSocket or SSE).
     */
    @field(String)
    protocol!: string;
}
