// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Cratis.Arc.Queries.QuerySubscriber. Time: 2026-10-03T11:15:01.4419310Z. Hash: 38F56170F38A57ED3462AE6FDB82D41C73D3E632E75EC57FA33E23EA9C7F2FD6
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';
import { QuerySubscriptionClientInfo } from './QuerySubscriptionClientInfo';

/**
 * Represents a single active subscriber for a query, combining connection and subscription data.
 */
export class QuerySubscriber {

    /**
     * Gets the connection identifier (e.g. `ws-1` for WebSocket, a GUID for SSE).
     */
    @field(String)
    connectionId!: string;

    /**
     * Gets the transport protocol (`WebSocket` or `SSE`).
     */
    @field(String)
    protocol!: string;

    /**
     * Gets the subscription identifier — the client-generated query ID.
     */
    @field(String)
    subscriptionId!: string;

    /**
     * Gets when this subscription was first established.
     */
    @field(Date)
    connectedAt!: Date;

    /**
     * Gets the last time a ping was sent to this subscriber.
     */
    @field(Date)
    lastPingSentAt?: Date;

    /**
     * Gets the last time a pong was received from this subscriber.
     */
    @field(Date)
    lastPongReceivedAt?: Date;

    /**
     * Gets the last time data was served to this subscriber.
     */
    @field(Date)
    lastDataServedAt?: Date;

    /**
     * Gets client identity and transport information for this subscriber.
     */
    @field(QuerySubscriptionClientInfo)
    clientInfo!: QuerySubscriptionClientInfo;
}
