// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Cratis.Arc.Queries.QueryConnectionHealth. Time: 2026-10-03T11:15:01.4419310Z. Hash: B0C5A35BC359C36FB30E4266501060C89B858CA8F201F3B950D901B86F98FC89
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';
import { QuerySubscriptionMetadata } from './QuerySubscriptionMetadata';

/**
 * Represents health information for a query connection.
 */
export class QueryConnectionHealth {

    /**
     * Gets the connection identifier.
     */
    @field(String)
    connectionId!: string;

    /**
     * Gets the connection protocol (WebSocket or SSE).
     */
    @field(String)
    protocol!: string;

    /**
     * Gets when the connection was established.
     */
    @field(Date)
    establishedAt!: Date;

    /**
     * Gets the subscriptions on this connection.
     */
    @field(QuerySubscriptionMetadata, true)
    subscriptions!: QuerySubscriptionMetadata[];
}
