// @generated by Cratis. Source: TestApps.ModelBoundReadModel, TestApps.ModelBoundReadModel, TestApps.ModelBoundReadModel. Time: 2026-07-20T10:41:40.5341110Z. Hash: 4D3D051665591FC9CEE1D028CD0CD37464132B4F31C02C9AD56623ED61218BCD
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, Sorting, Paging } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen, useQueryWithPaging, useSuspenseQueryWithPaging, SetPage, SetPageSize } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

export interface GetByIdParameters {
    id: string;
}


export class GetById extends QueryFor<ModelBoundReadModel, GetByIdParameters> {
    readonly route: string = '/api/get-by-id';
    readonly queryName: string = 'TestApps.ModelBoundReadModel.GetById';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ModelBoundReadModel = {} as any;

    constructor() {
        super(ModelBoundReadModel, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', String, false),
    ];

    id!: string;


    static use(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>, SetSorting] {
        return useQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
    }

    static useSuspense(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>, SetSorting] {
        return useSuspenseQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
    }

    static when(condition: boolean): QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters> {
        return new QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters>(GetById, condition);
    }
}

class GetAllSortBy {

    constructor(readonly query: GetAll) {
    }

}

class GetAllSortByWithoutQuery {

}


export class GetAll extends QueryFor<ModelBoundReadModel[]> {
    readonly route: string = '/api/get-all';
    readonly queryName: string = 'TestApps.ModelBoundReadModel.GetAll';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ModelBoundReadModel[] = [];
    private readonly _sortBy: GetAllSortBy;
    private static readonly _sortBy: GetAllSortByWithoutQuery = new GetAllSortByWithoutQuery();

    constructor() {
        super(ModelBoundReadModel, true);
        this._sortBy = new GetAllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): GetAllSortBy {
        return this._sortBy;
    }

    static get sortBy(): GetAllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting] {
        return useQuery<ModelBoundReadModel[], GetAll>(GetAll, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<ModelBoundReadModel[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting] {
        return useSuspenseQuery<ModelBoundReadModel[], GetAll>(GetAll, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<ModelBoundReadModel[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): QueryWhen<GetAll, ModelBoundReadModel[]> {
        return new QueryWhen<GetAll, ModelBoundReadModel[]>(GetAll, condition);
    }
}

export class ModelBoundReadModel {
    @field(Number)
    data!: number;
}
