// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.LiveFeed.LiveFeed. Time: 2026-10-03T11:15:01.4419310Z. Hash: 2C3E60F7E5CA837CCC22C62BC1C4B4C1D5C34437475730AFDA174611053BEFB0
// **DO NOT EDIT** - This file is an automatically generated file.
import { ChangeSet, ObservableQueryFor, Paging, QueryResultWithState, Sorting, SortingActions, SortingActionsForObservableQuery } from '@cratis/arc/queries';
import { ObservableQueryWhen, SetPage, SetPageSize, SetSorting, useChangeStream, useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { LiveFeed } from './LiveFeed';

class ByAuthorSortBy {
    private _author: SortingActionsForObservableQuery<LiveFeed[]>;

    constructor(readonly query: ByAuthor) {
        this._author = new SortingActionsForObservableQuery<LiveFeed[]>('author', query);
    }

    get author(): SortingActionsForObservableQuery<LiveFeed[]> {
        return this._author;
    }
}

class ByAuthorSortByWithoutQuery {
    private _author: SortingActions  = new SortingActions('author');

    get author(): SortingActions {
        return this._author;
    }
}

export interface ByAuthorParameters {

    author: string;
}


export class ByAuthor extends ObservableQueryFor<LiveFeed[], ByAuthorParameters> {
    readonly route: string = '/api/features/live-feed/by-author';
    readonly queryName: string = 'Samples.Features.LiveFeed.LiveFeed.ByAuthor';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: LiveFeed[] = [];
    private readonly _sortBy: ByAuthorSortBy;
    private static readonly _sortBy: ByAuthorSortByWithoutQuery = new ByAuthorSortByWithoutQuery();

    constructor() {
        super(LiveFeed, true);
        this._sortBy = new ByAuthorSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
            'author',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('author', String, false),
    ];

    author!: string;

    get sortBy(): ByAuthorSortBy {
        return this._sortBy;
    }

    static get sortBy(): ByAuthorSortByWithoutQuery {
        return this._sortBy;
    }

    static use(args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useObservableQuery<LiveFeed[], ByAuthor, ByAuthorParameters>(ByAuthor, args, sorting);
    }

    static useWithPaging(pageSize: number, args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<LiveFeed[], ByAuthor>(ByAuthor, new Paging(0, pageSize), args, sorting);
    }

    static useSuspense(args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useSuspenseObservableQuery<LiveFeed[], ByAuthor, ByAuthorParameters>(ByAuthor, args, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<LiveFeed[], ByAuthor>(ByAuthor, new Paging(0, pageSize), args, sorting);
    }

    static useChangeStream(args?: ByAuthorParameters, getKey?: (item: LiveFeed) => unknown, sorting?: Sorting): ChangeSet<LiveFeed> {
        return useChangeStream<LiveFeed, ByAuthor, ByAuthorParameters>(ByAuthor, args, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<ByAuthor, LiveFeed[], ByAuthorParameters> {
        return new ObservableQueryWhen<ByAuthor, LiveFeed[], ByAuthorParameters>(ByAuthor, condition);
    }
}
