// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.LiveFeed.LiveFeed. Time: 2026-10-03T11:15:01.4419310Z. Hash: FA0CC77664B11A94DF4BFF0754C46718F279CAC0BC5B31216C756A507261BB16
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';

export class LiveFeed {
    @field(String)
    author!: string;
    @field(String)
    text!: string;
    @field(Date)
    postedAt!: Date;
}
