// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: AspNetCore.Features.LiveFeed.LiveFeedController. Time: 2026-10-03T11:15:01.4419310Z. Hash: BA10CDCAABADC2F685CF300B42DB10DA06424DA8498DB224FCD982A0359FD750
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { LiveFeedMessage } from './LiveFeedMessage';

export interface IPost {
    author?: string;
    text?: string;
}


export class Post extends Command<IPost, LiveFeedMessage> implements IPost {
    readonly route: string = '/api/live-feed/post';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('author', String, false),
        new PropertyDescriptor('text', String, false),
    ];

    private _author!: string;
    private _text!: string;

    constructor() {
        super(LiveFeedMessage, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get author(): string {
        return this._author;
    }

    set author(value: string) {
        this._author = value;
        this.propertyChanged('author');
    }
    get text(): string {
        return this._text;
    }

    set text(value: string) {
        this._text = value;
        this.propertyChanged('text');
    }

    static use(initialValues?: IPost): [Post, SetCommandValues<IPost>, ClearCommandValues] {
        return useCommand<Post, IPost, LiveFeedMessage>(Post, initialValues);
    }
}
