// @generated by Cratis. Source: TestApps.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus. Time: 2026-04-12T11:05:06.1046764Z. Hash: D4B233D5B0D9E04D9168BC5F77029104463054FCAE6D3F6DB13B221A518BAB03
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

export class CrossCuttingAuthorizationStatus {
    @field(String)
    message!: string;
    @field(Date)
    checkedAt!: Date;
}
