// @generated by Cratis. Source: TestApps.Features.CrossCuttingAuthorization.RunSecuredCommand. Time: 2026-04-12T11:05:06.1046764Z. Hash: 4FA14BFB5565910FBDC96BAE4B345D0DBC7E7666F7CAED8A4DDADCE067C06120
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IRunSecuredCommand {
    message?: string;
}

export class RunSecuredCommandValidator extends CommandValidator<IRunSecuredCommand> {
    constructor() {
        super();
    }
}

export class RunSecuredCommand extends Command<IRunSecuredCommand, string> implements IRunSecuredCommand {
    readonly route: string = '/api/features/cross-cutting-authorization';
    readonly validation: CommandValidator = new RunSecuredCommandValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('message', String, false),
    ];

    private _message!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get message(): string {
        return this._message;
    }

    set message(value: string) {
        this._message = value;
        this.propertyChanged('message');
    }

    static use(initialValues?: IRunSecuredCommand): [RunSecuredCommand, SetCommandValues<IRunSecuredCommand>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RunSecuredCommand, IRunSecuredCommand>(RunSecuredCommand, initialValues);
    }
}
