// @generated by Cratis. Source: TestApps.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus. Time: 2026-05-06T11:10:29.7191050Z. Hash: BE5B387AA600C674C5DD37B1D1E60EB00158DB2F4B0734BE3583F058846B5406
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, QueryValidator } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { CrossCuttingAuthorizationStatus } from './CrossCuttingAuthorizationStatus';


export class SecuredValidator extends QueryValidator<object> {
    constructor() {
        super();
    }
}

export class Secured extends QueryFor<CrossCuttingAuthorizationStatus> {
    readonly route: string = '/api/features/cross-cutting-authorization/secured';
    readonly queryName: string = 'TestApps.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus.Secured';
    readonly validation: QueryValidator = new SecuredValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: CrossCuttingAuthorizationStatus = {} as any;

    constructor() {
        super(CrossCuttingAuthorizationStatus, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<CrossCuttingAuthorizationStatus>, PerformQuery, SetSorting] {
        return useQuery<CrossCuttingAuthorizationStatus, Secured>(Secured);
    }

    static useSuspense(): [QueryResultWithState<CrossCuttingAuthorizationStatus>, PerformQuery, SetSorting] {
        return useSuspenseQuery<CrossCuttingAuthorizationStatus, Secured>(Secured);
    }

    static when(condition: boolean): QueryWhen<Secured, CrossCuttingAuthorizationStatus> {
        return new QueryWhen<Secured, CrossCuttingAuthorizationStatus>(Secured, condition);
    }
}
