// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Arc.ProxyGenerator.for_GeneratedFileMetadata.when_parsing_comment_line;

public class with_valid_comment : Specification
{
    GeneratedFileMetadata? _metadata;
    bool _result;

    void Establish()
    {
    }

    void Because() => _result = GeneratedFileMetadata.TryParse(
        "// @generated by Cratis. Source: MyNamespace.MyClass. Time: 2024-12-08T10:00:00.0000000Z",
        out _metadata);

    [Fact] void should_return_true() => _result.ShouldBeTrue();
    [Fact] void should_have_metadata() => _metadata.ShouldNotBeNull();
    [Fact] void should_have_correct_source_type_name() => _metadata!.SourceTypeName.ShouldEqual("MyNamespace.MyClass");
    [Fact] void should_have_parsed_time() => _metadata!.GeneratedTime.Year.ShouldEqual(2024);
}
