// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Arc.ProxyGenerator.for_GeneratedFileMetadata.when_parsing_comment_line;

public class with_malformed_comment : Specification
{
    GeneratedFileMetadata? _metadata;
    bool _result;

    void Establish()
    {
    }

    void Because() => _result = GeneratedFileMetadata.TryParse(
        "// @generated by Cratis. Source: ",
        out _metadata);

    [Fact] void should_return_false() => _result.ShouldBeFalse();
    [Fact] void should_not_have_metadata() => _metadata.ShouldBeNull();
}
