// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.ObservableCollectionWithGuid.RemoveObservableCollectionWithGuidItem. Time: 2026-10-03T11:14:56.9415300Z. Hash: 202EE53AF6134DEE75A479118EA9CBE2F826A78B9EB2B62CF398EAB7469F375D
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface IRemoveObservableCollectionWithGuidItem {
    id?: Guid;
}


export class RemoveObservableCollectionWithGuidItem extends Command<IRemoveObservableCollectionWithGuidItem> implements IRemoveObservableCollectionWithGuidItem {
    readonly route: string = '/api/features/observable-collection-with-guid/remove-observable-collection-with-guid-item';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Guid, false),
    ];

    private _id!: Guid;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): Guid {
        return this._id;
    }

    set id(value: Guid) {
        this._id = value;
        this.propertyChanged('id');
    }

    static use(initialValues?: IRemoveObservableCollectionWithGuidItem): [RemoveObservableCollectionWithGuidItem, SetCommandValues<IRemoveObservableCollectionWithGuidItem>, ClearCommandValues] {
        return useCommand<RemoveObservableCollectionWithGuidItem, IRemoveObservableCollectionWithGuidItem>(RemoveObservableCollectionWithGuidItem, initialValues);
    }
}
