// @generated by Cratis. Source: TestApps.Features.ObservableCollectionWithGuid.ObservableCollectionWithGuidItem, TestApps.Features.ObservableCollectionWithGuid.ObservableCollectionWithGuidItem. Time: 2026-07-19T23:32:46.5273810Z. Hash: D4766729FF6B34A76C97DDDC148712D698DDDA99D43F004EACE4C82964418C42
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, QueryValidator, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';

class AllSortBy {

    constructor(readonly query: All) {
    }

}

class AllSortByWithoutQuery {

}

export class AllValidator extends QueryValidator<object> {
    constructor() {
        super();
    }
}

export class All extends ObservableQueryFor<ObservableCollectionWithGuidItem[]> {
    readonly route: string = '/api/features/observable-collection-with-guid/all';
    readonly queryName: string = 'TestApps.Features.ObservableCollectionWithGuid.ObservableCollectionWithGuidItem.All';
    readonly validation: QueryValidator = new AllValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ObservableCollectionWithGuidItem[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(ObservableCollectionWithGuidItem, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ObservableCollectionWithGuidItem[]>, SetSorting] {
        return useObservableQuery<ObservableCollectionWithGuidItem[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ObservableCollectionWithGuidItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ObservableCollectionWithGuidItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ObservableCollectionWithGuidItem[]>, SetSorting] {
        return useSuspenseObservableQuery<ObservableCollectionWithGuidItem[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ObservableCollectionWithGuidItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ObservableCollectionWithGuidItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: ObservableCollectionWithGuidItem) => unknown, sorting?: Sorting): ChangeSet<ObservableCollectionWithGuidItem> {
        return useChangeStream<ObservableCollectionWithGuidItem, All>(All, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, ObservableCollectionWithGuidItem[]> {
        return new ObservableQueryWhen<All, ObservableCollectionWithGuidItem[]>(All, condition);
    }
}

export class ObservableCollectionWithGuidItem {
    @field(Guid)
    id!: Guid;
    @field(String)
    label!: string;
}
