// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: AspNetCore.Commands. Time: 2026-10-07T12:29:11.8034443Z. Hash: E6EB92744F0AC31DEA2777E10AACFC7D71308A78B1A7CF69452D32BC1D84A738
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command, CommandValidator } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IDoStuff {
    stuffToDo?: string;
}

export class DoStuffValidator extends CommandValidator<IDoStuff> {
    constructor() {
        super();
        this.ruleFor(c => c.stuffToDo).notEmpty();
    }
}

export class DoStuff extends Command<IDoStuff, string> implements IDoStuff {
    readonly route: string = '/api/commands/do-stuff';
    readonly validation: CommandValidator = new DoStuffValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('stuffToDo', String, false),
    ];

    #stuffToDo!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get stuffToDo(): string {
        return this.#stuffToDo;
    }

    set stuffToDo(value: string) {
        this.#stuffToDo = value;
        this.propertyChanged('stuffToDo');
    }

    static use(initialValues?: IDoStuff): [DoStuff, SetCommandValues<IDoStuff>, ClearCommandValues] {
        return useCommand<DoStuff, IDoStuff, string>(DoStuff, initialValues);
    }
}
