// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.ModelBoundReadModel. Time: 2026-10-03T11:15:01.4419310Z. Hash: B4D2A8018C735D2BEA4AA8BCBE7FD045C4AA2C9F5737E0199ADAD7EE9D7FD53A
// **DO NOT EDIT** - This file is an automatically generated file.
import { Paging, QueryFor, QueryResultWithState, Sorting } from '@cratis/arc/queries';
import { PerformQuery, QueryWhen, SetPage, SetPageSize, SetSorting, useQuery, useQueryWithPaging, useSuspenseQuery, useSuspenseQueryWithPaging } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ModelBoundReadModel } from './ModelBoundReadModel';

class GetAllSortBy {

    constructor(readonly query: GetAll) {
    }

}

class GetAllSortByWithoutQuery {

}


export class GetAll extends QueryFor<ModelBoundReadModel[]> {
    readonly route: string = '/api/get-all';
    readonly queryName: string = 'Samples.ModelBoundReadModel.GetAll';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ModelBoundReadModel[] = [];
    private readonly _sortBy: GetAllSortBy;
    private static readonly _sortBy: GetAllSortByWithoutQuery = new GetAllSortByWithoutQuery();

    constructor() {
        super(ModelBoundReadModel, true);
        this._sortBy = new GetAllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): GetAllSortBy {
        return this._sortBy;
    }

    static get sortBy(): GetAllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting] {
        return useQuery<ModelBoundReadModel[], GetAll>(GetAll, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<ModelBoundReadModel[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting] {
        return useSuspenseQuery<ModelBoundReadModel[], GetAll>(GetAll, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<ModelBoundReadModel[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): QueryWhen<GetAll, ModelBoundReadModel[]> {
        return new QueryWhen<GetAll, ModelBoundReadModel[]>(GetAll, condition);
    }
}
