// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.ModelBoundReadModel. Time: 2026-10-03T11:15:01.4419310Z. Hash: 71E17DD6F00AB20CF4FE2CF41671988FB36DCA009273572355EDE35C9A77CEBE
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';

export class ModelBoundReadModel {
    @field(Number)
    data!: number;
}
