// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: AspNetCore.ObservableQueries. Time: 2026-10-03T11:15:01.4419310Z. Hash: 7EC84353291D478C4F17DC29BB026C60AB7DF8A1F61C4D219BA989440C9CC080
// **DO NOT EDIT** - This file is an automatically generated file.
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { ObservableQueryWhen, useObservableQuery, useSuspenseObservableQuery } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';



export class Messages extends ObservableQueryFor<string> {
    readonly route: string = '/api/observable-queries/messages';
    readonly queryName: string = 'AspNetCore.ObservableQueries.Messages';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: string = {} as string;

    constructor() {
        super(String, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<string>] {
        const [result] = useObservableQuery<string, Messages>(Messages);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<string>] {
        const [result] = useSuspenseObservableQuery<string, Messages>(Messages);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Messages, string> {
        return new ObservableQueryWhen<Messages, string>(Messages, condition);
    }
}
