// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.LiveFeed.LiveFeedMessage. Time: 2026-10-03T11:14:56.9415300Z. Hash: 069AFEC04BF8D7CCDF972AF346E023E3A3AA68BCC7E7464EFEC5A44853BFAFAB
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';

export class LiveFeedMessage {
    @field(String)
    author!: string;
    @field(String)
    text!: string;
    @field(Date)
    postedAt!: Date;
}
