// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.LiveFeed.LiveFeed, Samples.Features.LiveFeed.LiveFeed, Samples.Features.LiveFeed.LiveFeed. Time: 2026-10-09T23:44:00.5956700Z. Hash: 6965F82A0BF39BDF5EA29E279A8BDAE6B9B72A55072FDEED04E11B8A62D9B47E
// **DO NOT EDIT** - This file is an automatically generated file.
import { ChangeSet, ObservableQueryFor, Paging, QueryResultWithState, Sorting, SortingActions, SortingActionsForObservableQuery } from '@cratis/arc/queries';
import { ObservableQueryWhen, SetPage, SetPageSize, SetSorting, useChangeStream, useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

class AllSortBy {
    private _author: SortingActionsForObservableQuery<LiveFeed[]>;
    private _postedAt: SortingActionsForObservableQuery<LiveFeed[]>;
    private _text: SortingActionsForObservableQuery<LiveFeed[]>;

    constructor(readonly query: All) {
        this._author = new SortingActionsForObservableQuery<LiveFeed[]>('author', query);
        this._postedAt = new SortingActionsForObservableQuery<LiveFeed[]>('postedAt', query);
        this._text = new SortingActionsForObservableQuery<LiveFeed[]>('text', query);
    }

    get author(): SortingActionsForObservableQuery<LiveFeed[]> {
        return this._author;
    }
    get postedAt(): SortingActionsForObservableQuery<LiveFeed[]> {
        return this._postedAt;
    }
    get text(): SortingActionsForObservableQuery<LiveFeed[]> {
        return this._text;
    }
}

class AllSortByWithoutQuery {
    private _author: SortingActions  = new SortingActions('author');
    private _postedAt: SortingActions  = new SortingActions('postedAt');
    private _text: SortingActions  = new SortingActions('text');

    get author(): SortingActions {
        return this._author;
    }
    get postedAt(): SortingActions {
        return this._postedAt;
    }
    get text(): SortingActions {
        return this._text;
    }
}


export class All extends ObservableQueryFor<LiveFeed[]> {
    readonly route: string = '/api/features/live-feed/all';
    readonly queryName: string = 'Samples.Features.LiveFeed.LiveFeed.All';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: LiveFeed[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(LiveFeed, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useObservableQuery<LiveFeed[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<LiveFeed[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useSuspenseObservableQuery<LiveFeed[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<LiveFeed[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: LiveFeed) => unknown, sorting?: Sorting): ChangeSet<LiveFeed> {
        return useChangeStream<LiveFeed, All>(All, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, LiveFeed[]> {
        return new ObservableQueryWhen<All, LiveFeed[]>(All, condition);
    }
}

class ByAuthorSortBy {
    private _author: SortingActionsForObservableQuery<LiveFeed[]>;
    private _postedAt: SortingActionsForObservableQuery<LiveFeed[]>;
    private _text: SortingActionsForObservableQuery<LiveFeed[]>;

    constructor(readonly query: ByAuthor) {
        this._author = new SortingActionsForObservableQuery<LiveFeed[]>('author', query);
        this._postedAt = new SortingActionsForObservableQuery<LiveFeed[]>('postedAt', query);
        this._text = new SortingActionsForObservableQuery<LiveFeed[]>('text', query);
    }

    get author(): SortingActionsForObservableQuery<LiveFeed[]> {
        return this._author;
    }
    get postedAt(): SortingActionsForObservableQuery<LiveFeed[]> {
        return this._postedAt;
    }
    get text(): SortingActionsForObservableQuery<LiveFeed[]> {
        return this._text;
    }
}

class ByAuthorSortByWithoutQuery {
    private _author: SortingActions  = new SortingActions('author');
    private _postedAt: SortingActions  = new SortingActions('postedAt');
    private _text: SortingActions  = new SortingActions('text');

    get author(): SortingActions {
        return this._author;
    }
    get postedAt(): SortingActions {
        return this._postedAt;
    }
    get text(): SortingActions {
        return this._text;
    }
}

export interface ByAuthorParameters {

    author: string;
}


export class ByAuthor extends ObservableQueryFor<LiveFeed[], ByAuthorParameters> {
    readonly route: string = '/api/features/live-feed/by-author';
    readonly queryName: string = 'Samples.Features.LiveFeed.LiveFeed.ByAuthor';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: LiveFeed[] = [];
    private readonly _sortBy: ByAuthorSortBy;
    private static readonly _sortBy: ByAuthorSortByWithoutQuery = new ByAuthorSortByWithoutQuery();

    constructor() {
        super(LiveFeed, true);
        this._sortBy = new ByAuthorSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
            'author',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('author', String, false),
    ];

    author!: string;

    get sortBy(): ByAuthorSortBy {
        return this._sortBy;
    }

    static get sortBy(): ByAuthorSortByWithoutQuery {
        return this._sortBy;
    }

    static use(args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useObservableQuery<LiveFeed[], ByAuthor, ByAuthorParameters>(ByAuthor, args, sorting);
    }

    static useWithPaging(pageSize: number, args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<LiveFeed[], ByAuthor>(ByAuthor, new Paging(0, pageSize), args, sorting);
    }

    static useSuspense(args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useSuspenseObservableQuery<LiveFeed[], ByAuthor, ByAuthorParameters>(ByAuthor, args, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<LiveFeed[], ByAuthor>(ByAuthor, new Paging(0, pageSize), args, sorting);
    }

    static useChangeStream(args?: ByAuthorParameters, getKey?: (item: LiveFeed) => unknown, sorting?: Sorting): ChangeSet<LiveFeed> {
        return useChangeStream<LiveFeed, ByAuthor, ByAuthorParameters>(ByAuthor, args, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<ByAuthor, LiveFeed[], ByAuthorParameters> {
        return new ObservableQueryWhen<ByAuthor, LiveFeed[], ByAuthorParameters>(ByAuthor, condition);
    }
}

export class LiveFeed {
    @field(String)
    author!: string;
    @field(String)
    text!: string;
    @field(Date)
    postedAt!: Date;
}
