// @generated by Cratis. Source: AspNetCore.Commands. Time: 2026-03-22T09:12:01.2170493Z. Hash: combined
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IDoStuff {
    stuffToDo?: string;
}

export class DoStuffValidator extends CommandValidator<IDoStuff> {
    constructor() {
        super();
    }
}

export class DoStuff extends Command<IDoStuff, string> implements IDoStuff {
    readonly route: string = '/api/commands/do-stuff';
    readonly validation: CommandValidator = new DoStuffValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('stuffToDo', String, false),
    ];

    private _stuffToDo!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get stuffToDo(): string {
        return this._stuffToDo;
    }

    set stuffToDo(value: string) {
        this._stuffToDo = value;
        this.propertyChanged('stuffToDo');
    }

    static use(initialValues?: IDoStuff): [DoStuff, SetCommandValues<IDoStuff>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<DoStuff, IDoStuff>(DoStuff, initialValues);
    }
}
