// @generated by Cratis. Source: AspNetCore.LiveFeedMessage. Time: 2026-03-22T09:12:01.2665077Z. Hash: combined
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

export class LiveFeedMessage {
    @field(String)
    author!: string;
    @field(String)
    text!: string;
    @field(Date)
    postedAt!: Date;
}
