// @generated by Cratis. Source: AspNetCore.LiveFeed. Time: 2026-03-22T09:12:01.2621591Z. Hash: combined
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { ObservableQueryFor, QueryResultWithState, Sorting, SortingActions, SortingActionsForObservableQuery, Paging } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';

export class LiveFeed {
    @field(String)
    author!: string;
    @field(String)
    text!: string;
    @field(Date)
    postedAt!: Date;
}

class AllSortBy {

    constructor(readonly query: All) {
    }

}

class AllSortByWithoutQuery {

}

export class All extends ObservableQueryFor<LiveFeed[]> {
    readonly route: string = '/api/asp-net-core/all';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: LiveFeed[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(LiveFeed, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useObservableQuery<LiveFeed[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<LiveFeed[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useSuspenseObservableQuery<LiveFeed[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<LiveFeed[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, LiveFeed[]> {
        return new ObservableQueryWhen<All, LiveFeed[]>(All, condition);
    }
}

class ByAuthorSortBy {
    private _author: SortingActionsForObservableQuery<LiveFeed[]>;

    constructor(readonly query: ByAuthor) {
        this._author = new SortingActionsForObservableQuery<LiveFeed[]>('author', query);
    }

    get author(): SortingActionsForObservableQuery<LiveFeed[]> {
        return this._author;
    }
}

class ByAuthorSortByWithoutQuery {
    private _author: SortingActions  = new SortingActions('author');

    get author(): SortingActions {
        return this._author;
    }
}

export interface ByAuthorParameters {
    
    author: string;
}
export class ByAuthor extends ObservableQueryFor<LiveFeed[], ByAuthorParameters> {
    readonly route: string = '/api/asp-net-core/by-author';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: LiveFeed[] = [];
    private readonly _sortBy: ByAuthorSortBy;
    private static readonly _sortBy: ByAuthorSortByWithoutQuery = new ByAuthorSortByWithoutQuery();

    constructor() {
        super(LiveFeed, true);
        this._sortBy = new ByAuthorSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
            'author',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('author', String),
    ];

    author!: string;

    get sortBy(): ByAuthorSortBy {
        return this._sortBy;
    }

    static get sortBy(): ByAuthorSortByWithoutQuery {
        return this._sortBy;
    }

    static use(args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useObservableQuery<LiveFeed[], ByAuthor, ByAuthorParameters>(ByAuthor, args, sorting);
    }

    static useWithPaging(pageSize: number, args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<LiveFeed[], ByAuthor>(ByAuthor, new Paging(0, pageSize), args, sorting);
    }

    static useSuspense(args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useSuspenseObservableQuery<LiveFeed[], ByAuthor, ByAuthorParameters>(ByAuthor, args, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<LiveFeed[], ByAuthor>(ByAuthor, new Paging(0, pageSize), args, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<ByAuthor, LiveFeed[], ByAuthorParameters> {
        return new ObservableQueryWhen<ByAuthor, LiveFeed[], ByAuthorParameters>(ByAuthor, condition);
    }
}
