// @generated by Cratis. Source: AspNetCore.Commands. Time: 2026-07-28T00:03:13.2306963Z. Hash: D3BA254234A8075246917BD0D078B3146CA866702D82B3B6A5363CB3A581FC9F
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IDoStuff {
    stuffToDo?: string;
}

export class DoStuffValidator extends CommandValidator<IDoStuff> {
    constructor() {
        super();
        this.ruleFor(c => c.stuffToDo).notEmpty();
    }
}

export class DoStuff extends Command<IDoStuff, string> implements IDoStuff {
    readonly route: string = '/api/commands/do-stuff';
    readonly validation: CommandValidator = new DoStuffValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('stuffToDo', String, false),
    ];

    private _stuffToDo!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get stuffToDo(): string {
        return this._stuffToDo;
    }

    set stuffToDo(value: string) {
        this._stuffToDo = value;
        this.propertyChanged('stuffToDo');
    }

    static use(initialValues?: IDoStuff): [DoStuff, SetCommandValues<IDoStuff>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<DoStuff, IDoStuff>(DoStuff, initialValues);
    }
}
