// @generated by Cratis. Source: AspNetCore.Commands. Time: 2026-07-20T10:41:43.4511480Z. Hash: 2090479FF118BD7B90B49E095E165B4F4114EE21A60D29ED3BE8F11C8382CC45
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IDoStuff {
    stuffToDo?: string;
}


export class DoStuff extends Command<IDoStuff, string> implements IDoStuff {
    readonly route: string = '/api/commands/do-stuff';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('stuffToDo', String, false),
    ];

    private _stuffToDo!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get stuffToDo(): string {
        return this._stuffToDo;
    }

    set stuffToDo(value: string) {
        this._stuffToDo = value;
        this.propertyChanged('stuffToDo');
    }

    static use(initialValues?: IDoStuff): [DoStuff, SetCommandValues<IDoStuff>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<DoStuff, IDoStuff>(DoStuff, initialValues);
    }
}
