// @generated by Cratis. Source: TestApps.ModelBoundReadModel. Time: 2026-07-20T10:41:43.4511480Z. Hash: 360FB850DCFCC52086746EA9BD625328D2ED352EDFB6A018B08E6D3C7BEFAFE2
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, Sorting, Paging } from '@cratis/arc/queries';
import { useQuery, useQueryWithPaging, useSuspenseQuery, useSuspenseQueryWithPaging, PerformQuery, SetSorting, SetPage, SetPageSize, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ModelBoundReadModel } from './ModelBoundReadModel';

class GetAllSortBy {

    constructor(readonly query: GetAll) {
    }

}

class GetAllSortByWithoutQuery {

}


export class GetAll extends QueryFor<ModelBoundReadModel[]> {
    readonly route: string = '/api/get-all';
    readonly queryName: string = 'TestApps.ModelBoundReadModel.GetAll';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ModelBoundReadModel[] = [];
    private readonly _sortBy: GetAllSortBy;
    private static readonly _sortBy: GetAllSortByWithoutQuery = new GetAllSortByWithoutQuery();

    constructor() {
        super(ModelBoundReadModel, true);
        this._sortBy = new GetAllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): GetAllSortBy {
        return this._sortBy;
    }

    static get sortBy(): GetAllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting] {
        return useQuery<ModelBoundReadModel[], GetAll>(GetAll, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<ModelBoundReadModel[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting] {
        return useSuspenseQuery<ModelBoundReadModel[], GetAll>(GetAll, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ModelBoundReadModel[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<ModelBoundReadModel[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): QueryWhen<GetAll, ModelBoundReadModel[]> {
        return new QueryWhen<GetAll, ModelBoundReadModel[]>(GetAll, condition);
    }
}
