// @generated by Cratis. Source: TestApps.ModelBoundReadModel. Time: 2026-03-26T10:40:07.6866700Z. Hash: AB00B946C726A651F68C5163E70E42FE300FBC9D51C975F3F16F74812B59238A
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, QueryValidator } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ModelBoundReadModel } from './ModelBoundReadModel';


export interface GetByIdParameters {
    id: string;
}

export class GetByIdValidator extends QueryValidator<GetByIdParameters> {
    constructor() {
        super();
    }
}

export class GetById extends QueryFor<ModelBoundReadModel, GetByIdParameters> {
    readonly route: string = '/api/get-by-id';
    readonly validation: QueryValidator = new GetByIdValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ModelBoundReadModel = {} as any;

    constructor() {
        super(ModelBoundReadModel, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', String),
    ];

    id!: string;


    static use(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>] {
        const [result, perform] = useQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
        return [result, perform];
    }

    static useSuspense(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>] {
        const [result, perform] = useSuspenseQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
        return [result, perform];
    }

    static when(condition: boolean): QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters> {
        return new QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters>(GetById, condition);
    }
}
