// @generated by Cratis. Source: TestApps.ModelBoundReadModel. Time: 2026-05-06T11:10:29.7191050Z. Hash: BE40812BDBF63A53BADBD41CF8550AE7CA8D5444A989811DD85ABD6A8D127A55
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, QueryValidator } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ModelBoundReadModel } from './ModelBoundReadModel';


export interface GetByIdParameters {
    id: string;
}

export class GetByIdValidator extends QueryValidator<GetByIdParameters> {
    constructor() {
        super();
    }
}

export class GetById extends QueryFor<ModelBoundReadModel, GetByIdParameters> {
    readonly route: string = '/api/get-by-id';
    readonly queryName: string = 'TestApps.ModelBoundReadModel.GetById';
    readonly validation: QueryValidator = new GetByIdValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ModelBoundReadModel = {} as any;

    constructor() {
        super(ModelBoundReadModel, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', String, false),
    ];

    id!: string;


    static use(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>, SetSorting] {
        return useQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
    }

    static useSuspense(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>, SetSorting] {
        return useSuspenseQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
    }

    static when(condition: boolean): QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters> {
        return new QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters>(GetById, condition);
    }
}
