// @generated by Cratis. Source: TestApps.ModelBoundReadModel. Time: 2026-09-06T08:22:30.3863580Z. Hash: CD9B51527C7AFBFA7C782B8C32AFB182BBA7887B2204EC7D569642D1643A2EBB
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ModelBoundReadModel } from './ModelBoundReadModel';


export interface GetByIdParameters {
    id: string;
}


export class GetById extends QueryFor<ModelBoundReadModel, GetByIdParameters> {
    readonly route: string = '/api/get-by-id';
    readonly queryName: string = 'TestApps.ModelBoundReadModel.GetById';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ModelBoundReadModel = {} as ModelBoundReadModel;

    constructor() {
        super(ModelBoundReadModel, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', String, false),
    ];

    id!: string;


    static use(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>, SetSorting] {
        return useQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
    }

    static useSuspense(args?: GetByIdParameters): [QueryResultWithState<ModelBoundReadModel>, PerformQuery<GetByIdParameters>, SetSorting] {
        return useSuspenseQuery<ModelBoundReadModel, GetById, GetByIdParameters>(GetById, args);
    }

    static when(condition: boolean): QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters> {
        return new QueryWhen<GetById, ModelBoundReadModel, GetByIdParameters>(GetById, condition);
    }
}
