// @generated by Cratis. Source: AspNetCore.LiveFeedController. Time: 2026-03-23T06:57:42.8867450Z. Hash: BDBB4F7AF49857FDFE620737FF10A676E238D06B6EC8F7E3D22CAA670F281D53
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { LiveFeedMessage } from './LiveFeedMessage';

export interface IPost {
    author?: string;
    text?: string;
}

export class PostValidator extends CommandValidator<IPost> {
    constructor() {
        super();
    }
}

export class Post extends Command<IPost, LiveFeedMessage> implements IPost {
    readonly route: string = '/api/live-feed/post';
    readonly validation: CommandValidator = new PostValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('author', String, false),
        new PropertyDescriptor('text', String, false),
    ];

    private _author!: string;
    private _text!: string;

    constructor() {
        super(LiveFeedMessage, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get author(): string {
        return this._author;
    }

    set author(value: string) {
        this._author = value;
        this.propertyChanged('author');
    }
    get text(): string {
        return this._text;
    }

    set text(value: string) {
        this._text = value;
        this.propertyChanged('text');
    }

    static use(initialValues?: IPost): [Post, SetCommandValues<IPost>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<Post, IPost>(Post, initialValues);
    }
}
