// @generated by Cratis. Source: AspNetCore.ModelBoundCommand. Time: 2026-03-22T20:03:31.6560680Z. Hash: EC38694A64ACF68B25C66965969662E3C59271C93CAB20F718138579F316355C
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IModelBoundCommand {
    stuffToDo?: string;
}

export class ModelBoundCommandValidator extends CommandValidator<IModelBoundCommand> {
    constructor() {
        super();
    }
}

export class ModelBoundCommand extends Command<IModelBoundCommand, string> implements IModelBoundCommand {
    readonly route: string = '/api/model-bound-command';
    readonly validation: CommandValidator = new ModelBoundCommandValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('stuffToDo', String, false),
    ];

    private _stuffToDo!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get stuffToDo(): string {
        return this._stuffToDo;
    }

    set stuffToDo(value: string) {
        this._stuffToDo = value;
        this.propertyChanged('stuffToDo');
    }

    static use(initialValues?: IModelBoundCommand): [ModelBoundCommand, SetCommandValues<IModelBoundCommand>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ModelBoundCommand, IModelBoundCommand>(ModelBoundCommand, initialValues);
    }
}
