// @generated by Cratis. Source: TestApps.ModelBoundCommand. Time: 2026-07-20T10:41:43.4511480Z. Hash: C61472AF63ED40D86AB07B46E6ACA1D997BD7D69BF027B9888AC121ABEC173D1
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IModelBoundCommand {
    stuffToDo?: string;
}


export class ModelBoundCommand extends Command<IModelBoundCommand, string> implements IModelBoundCommand {
    readonly route: string = '/api';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('stuffToDo', String, false),
    ];

    private _stuffToDo!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get stuffToDo(): string {
        return this._stuffToDo;
    }

    set stuffToDo(value: string) {
        this._stuffToDo = value;
        this.propertyChanged('stuffToDo');
    }

    static use(initialValues?: IModelBoundCommand): [ModelBoundCommand, SetCommandValues<IModelBoundCommand>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ModelBoundCommand, IModelBoundCommand>(ModelBoundCommand, initialValues);
    }
}
