// @generated by Cratis. Source: AspNetCore.ObservableQueries. Time: 2026-07-19T23:32:51.1097230Z. Hash: D9C252D6F076873532115592C07ADC462D570F743EE4F28E046DC6E7B8D9C2B4
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, QueryValidator } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';


export class MessagesValidator extends QueryValidator<object> {
    constructor() {
        super();
    }
}

export class Messages extends ObservableQueryFor<string> {
    readonly route: string = '/api/observable-queries/messages';
    readonly queryName: string = 'AspNetCore.ObservableQueries.Messages';
    readonly validation: QueryValidator = new MessagesValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: string = {} as any;

    constructor() {
        super(String, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<string>] {
        const [result] = useObservableQuery<string, Messages>(Messages);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<string>] {
        const [result] = useSuspenseObservableQuery<string, Messages>(Messages);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Messages, string> {
        return new ObservableQueryWhen<Messages, string>(Messages, condition);
    }
}
