// @generated by Cratis. Source: AspNetCore.PostToFeed. Time: 2026-03-22T17:47:01.4178210Z. Hash: 623411DF035791FE0016206B9AF0C08E3EACB1AE272CA5847142DDB0D42EC4B6
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { LiveFeedMessage } from './LiveFeedMessage';

export interface IPostToFeed {
    author?: string;
    text?: string;
}

export class PostToFeedValidator extends CommandValidator<IPostToFeed> {
    constructor() {
        super();
    }
}

export class PostToFeed extends Command<IPostToFeed, LiveFeedMessage> implements IPostToFeed {
    readonly route: string = '/api//post-to-feed';
    readonly validation: CommandValidator = new PostToFeedValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('author', String, false),
        new PropertyDescriptor('text', String, false),
    ];

    private _author!: string;
    private _text!: string;

    constructor() {
        super(LiveFeedMessage, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get author(): string {
        return this._author;
    }

    set author(value: string) {
        this._author = value;
        this.propertyChanged('author');
    }
    get text(): string {
        return this._text;
    }

    set text(value: string) {
        this._text = value;
        this.propertyChanged('text');
    }

    static use(initialValues?: IPostToFeed): [PostToFeed, SetCommandValues<IPostToFeed>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<PostToFeed, IPostToFeed>(PostToFeed, initialValues);
    }
}
