// @generated by Cratis. Source: AspNetCore.Ticker, AspNetCore.Ticker. Time: 2026-03-23T06:57:42.8867450Z. Hash: 101FDA565B4ACFE14528E4461C6C4D411D32898C0E33F79B8C32566EF83BD2C7
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

export class Observe extends ObservableQueryFor<Ticker> {
    readonly route: string = '/api/observe';
    readonly queryName: string = 'AspNetCore.Ticker.Observe';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Ticker = {} as any;

    constructor() {
        super(Ticker, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<Ticker>] {
        const [result] = useObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<Ticker>] {
        const [result] = useSuspenseObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Observe, Ticker> {
        return new ObservableQueryWhen<Observe, Ticker>(Observe, condition);
    }
}

export class Ticker {
    @field(Number)
    count!: number;
    @field(Date)
    lastUpdated!: Date;
}
