// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Arc.ProxyGenerator.for_IndexFileManager.when_updating_all_index_files;

public class with_a_hand_written_folder_barrel_under_the_output_path : Specification
{
    string _outputPath;
    string _widgetsDir;
    string _widgetsIndexPath;
    string _listIndexPath;
    const string ListBarrelContent = "export * from './WidgetListItem';\n";

    void Establish()
    {
        _outputPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        _widgetsDir = Path.Combine(_outputPath, "Widgets");
        Directory.CreateDirectory(_widgetsDir);

        // A generated file in the tracked directory.
        File.WriteAllText(Path.Combine(_widgetsDir, "WidgetOne.ts"), "// @generated by Cratis. Source: WidgetOne. Time: 2025-01-01T00:00:00.0000000Z. Hash: ABC\nexport class WidgetOne {}");

        // A hand-written sibling folder with its own barrel, nested under the output path. Discovered by
        // the "scan for any index.ts under outputPath" sweep, alongside the tracked Widgets directory.
        var listDir = Path.Combine(_widgetsDir, "List");
        Directory.CreateDirectory(listDir);
        _listIndexPath = Path.Combine(listDir, "index.ts");
        File.WriteAllText(_listIndexPath, ListBarrelContent);

        _widgetsIndexPath = Path.Combine(_widgetsDir, "index.ts");
        File.WriteAllText(_widgetsIndexPath, "export * from './WidgetOne';\nexport * from './List';\n");
    }

    void Because()
    {
        var dict = new Dictionary<string, GeneratedFileMetadata>
        {
            [Path.Combine(_widgetsDir, "WidgetOne.ts")] = new GeneratedFileMetadata("WidgetOne", DateTime.UtcNow, GeneratedFileMetadata.ComputeHash(""), false),
        };

        // Only the tracked Widgets directory is passed explicitly — the List folder barrel is discovered
        // through the outputPath-wide scan for existing index.ts files.
        IndexFileManager.UpdateAllIndexFiles([_widgetsDir], dict, [], _ => { }, _outputPath);
    }

    [Fact] void should_preserve_folder_export_in_tracked_index() => File.ReadAllText(_widgetsIndexPath).ShouldContain("export * from './List';");
    [Fact] void should_keep_generated_export_in_tracked_index() => File.ReadAllText(_widgetsIndexPath).ShouldContain("export * from './WidgetOne';");
    [Fact] void should_leave_the_folder_barrel_itself_untouched() => File.ReadAllText(_listIndexPath).ShouldEqual(ListBarrelContent);

    void Cleanup()
    {
        if (Directory.Exists(_outputPath))
        {
            Directory.Delete(_outputPath, true);
        }
    }
}
