// An ESLint flat-config processor that skips Cratis-generated proxy files wholesale.
//
// Arc's ProxyGenerator emits a `// @generated by Cratis …` line as line 1 (see
// GeneratedFileMetadata.cs) followed by a `**DO NOT EDIT** - This file is an
// automatically generated file.` banner (the Handlebars templates). These files cannot
// be edited — they are regenerated by `dotnet build -c Release` — so every lint finding
// on them is un-actionable, and an autofix would rewrite a file the next build reverts.
//
// Generated `.ts` proxies are co-located with hand-written `.ts` (view models, helpers)
// with no path or naming distinction, so the header is the only reliable signal — hence
// a content-sniffing processor rather than an `ignores` glob. `preprocess` returns `[]`
// (no lintable blocks) for a generated file and the file unchanged for everything else.
// The pass-through preserves the original filename, so import resolution is unaffected,
// and `supportsAutofix` keeps `--fix` working on the hand-written files that flow through.

const GENERATED_HEADER = '// @generated by Cratis';
const DO_NOT_EDIT_BANNER = '**DO NOT EDIT** - This file is an automatically generated file.';

export const isGeneratedProxy = text => {
    if (typeof text !== 'string') return false;
    if (text.startsWith(GENERATED_HEADER)) return true;
    // Fallback for any generator variant that omits the @generated line: the DO NOT EDIT
    // banner the templates emit within the first handful of lines.
    return text.split('\n', 4).join('\n').includes(DO_NOT_EDIT_BANNER);
};

export const skipGeneratedProxies = {
    meta: { name: '@cratis/arc/skip-generated-proxies' },
    preprocess(text) {
        return isGeneratedProxy(text) ? [] : [text];
    },
    postprocess(messages) {
        return messages.flat();
    },
    supportsAutofix: true,
};

export default skipGeneratedProxies;
