// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Security.Cryptography;
using System.Text;

namespace Cratis.Arc.ProxyGenerator;

/// <summary>
/// Represents metadata about a generated file.
/// </summary>
/// <param name="SourceTypeName">The full name of the source type.</param>
/// <param name="GeneratedTime">The date and time when the file was generated.</param>
/// <param name="ContentHash">SHA256 hash of the file content (excluding the metadata comment line).</param>
public record GeneratedFileMetadata(string SourceTypeName, DateTime GeneratedTime, string ContentHash = "")
{
    const string GeneratedMarker = "// @generated by Cratis";

    /// <summary>
    /// Creates a comment line for the generated file.
    /// </summary>
    /// <returns>The comment line to be added as the first line of the file.</returns>
    public string ToCommentLine() =>
        $"{GeneratedMarker}. Source: {SourceTypeName}. Time: {GeneratedTime:O}. Hash: {ContentHash}";

    /// <summary>
    /// Computes the SHA256 hash of the given content.
    /// </summary>
    /// <param name="content">The content to hash.</param>
    /// <returns>The hex string representation of the hash.</returns>
    public static string ComputeHash(string content)
    {
        var bytes = Encoding.UTF8.GetBytes(content);
        var hash = SHA256.HashData(bytes);
        return Convert.ToHexString(hash);
    }

    /// <summary>
    /// Tries to parse metadata from the first line of a file.
    /// </summary>
    /// <param name="firstLine">The first line of the file.</param>
    /// <param name="metadata">The parsed metadata if successful.</param>
    /// <returns>True if parsing was successful, false otherwise.</returns>
    public static bool TryParse(string firstLine, out GeneratedFileMetadata? metadata)
    {
        metadata = null;

        if (!firstLine.StartsWith(GeneratedMarker))
        {
            return false;
        }

        try
        {
            const string sourcePrefix = "Source: ";
            const string timePrefix = "Time: ";
            const string hashPrefix = "Hash: ";
            const string separator = ". ";

            var sourceIndex = firstLine.IndexOf(sourcePrefix);
            var timeIndex = firstLine.IndexOf(timePrefix);
            var hashIndex = firstLine.IndexOf(hashPrefix);

            if (sourceIndex == -1 || timeIndex == -1)
            {
                return false;
            }

            var sourceStart = sourceIndex + sourcePrefix.Length;
            var sourceEnd = timeIndex - separator.Length;
            if (sourceEnd <= sourceStart)
            {
                return false;
            }

            var sourceName = firstLine.Substring(sourceStart, sourceEnd - sourceStart).Trim();

            var timeStart = timeIndex + timePrefix.Length;
            var timeEnd = hashIndex > 0 ? hashIndex - separator.Length : firstLine.Length;
            var timeString = firstLine.Substring(timeStart, timeEnd - timeStart).Trim();

            var hash = string.Empty;
            if (hashIndex > 0)
            {
                var hashStart = hashIndex + hashPrefix.Length;
                hash = firstLine.Substring(hashStart).Trim();
            }

            if (DateTime.TryParse(timeString, out var time))
            {
                metadata = new GeneratedFileMetadata(sourceName, time, hash);
                return true;
            }
        }
        catch
        {
            // If any parsing fails, return false
        }

        return false;
    }

    /// <summary>
    /// Checks if a file contains the generated marker.
    /// </summary>
    /// <param name="filePath">The path to the file to check.</param>
    /// <param name="metadata">The parsed metadata if the file is generated.</param>
    /// <returns>True if the file contains the generated marker, false otherwise.</returns>
    public static bool IsGeneratedFile(string filePath, out GeneratedFileMetadata? metadata)
    {
        metadata = null;

        if (!File.Exists(filePath))
        {
            return false;
        }

        try
        {
            using var reader = new StreamReader(filePath);
            var firstLine = reader.ReadLine();
            if (firstLine is null)
            {
                return false;
            }

            return TryParse(firstLine, out metadata);
        }
        catch
        {
            return false;
        }
    }
}
