// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text.RegularExpressions;

namespace Cratis.Arc.ProxyGenerator;

/// <summary>
/// Provides functionality to intelligently manage index.ts files.
/// </summary>
public static partial class IndexFileManager
{
    /// <summary>
    /// Updates or creates an index.ts file for a directory, preserving manual edits.
    /// </summary>
    /// <param name="directory">The directory to create/update the index.ts file in.</param>
    /// <param name="generatedFiles">Dictionary of generated file paths (full paths) to their metadata.</param>
    /// <param name="orphanedFiles">Collection of orphaned file paths that were deleted.</param>
    /// <param name="message">Logger to use for outputting messages.</param>
    /// <param name="outputPath">The base output path for relative path calculation.</param>
    /// <returns>True if the index file was written, false if skipped.</returns>
    public static bool UpdateIndexFile(string directory, IDictionary<string, GeneratedFileMetadata> generatedFiles, IEnumerable<string> orphanedFiles, Action<string> message, string outputPath)
    {
        var indexPath = Path.Combine(directory, "index.ts");

        // Filter to only files in this directory and extract their names
        var fileNames = generatedFiles.Keys
            .Where(f => Path.GetDirectoryName(f) == directory)
            .Select(f => Path.GetFileNameWithoutExtension(f))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        // If there are no generated files in this directory, only delete the
        // existing index.ts if it was itself generated by this tool. Hand-written
        // index files are never touched regardless of their content.
        if (fileNames.Count == 0)
        {
            if (File.Exists(indexPath))
            {
                if (!GeneratedFileMetadata.IsGeneratedFile(indexPath, out _))
                {
                    return false;
                }

                if (HasLiveNonGeneratedExports(indexPath, directory))
                {
                    return false;
                }

                File.Delete(indexPath);
                message($"    Deleted empty index: {GetRelativePath(outputPath, indexPath)}");
            }
            return false;
        }

        var existingExports = new List<string>();
        var manualLines = new List<string>();

        // Parse existing index file if it exists
        if (File.Exists(indexPath))
        {
            foreach (var line in File.ReadAllLines(indexPath))
            {
                var match = ExportRegex().Match(line);
                if (match.Success)
                {
                    var exportPath = match.Groups["path"].Value;
                    existingExports.Add(exportPath);
                }
                else if (!string.IsNullOrWhiteSpace(line))
                {
                    // Keep non-export lines (comments, imports, etc.)
                    manualLines.Add(line);
                }
            }
        }

        // Build set of orphaned file names in this directory
        var orphanedFileNames = orphanedFiles
            .Where(f => Path.GetDirectoryName(f) == directory)
            .Select(f => Path.GetFileNameWithoutExtension(f))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        // Check if we need to update: new files were written, orphans exist, or
        // the existing index has exports pointing to files that no longer exist on disk.
        var anyWrittenInDirectory = generatedFiles.Any(kv => Path.GetDirectoryName(kv.Key) == directory && kv.Value.WasWritten);
        var hasOrphansInDirectory = orphanedFileNames.Count > 0;
        var hasStaleExports = existingExports.Exists(e =>
        {
            var fileName = e.TrimStart('.', '/');
            return !ExportTargetExistsOnDisk(directory, fileName) && !generatedFiles.ContainsKey(Path.GetFullPath(Path.Combine(directory, $"{fileName}.ts")));
        });

        if (!anyWrittenInDirectory && !hasOrphansInDirectory && !hasStaleExports)
        {
            return false;
        }

        // Build the final export list by inserting new exports individually at their best-effort alphabetical positions
        var existingFileNames = existingExports.Select(e => e.TrimStart('.', '/')).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var newExportsToAdd = new List<string>();

        // Collect new exports to add (only those not already in the index)
        foreach (var fileName in fileNames)
        {
            if (!existingFileNames.Contains(fileName))
            {
                newExportsToAdd.Add(fileName);
            }
        }

        // Start with existing exports, removing orphans and exports for files that
        // no longer exist on disk (e.g. after source file grouping changes).
        var finalExports = new List<string>();
        foreach (var export in existingExports)
        {
            var fileName = export.TrimStart('.', '/');

            // Skip orphaned exports
            if (orphanedFileNames.Contains(fileName))
            {
                continue;
            }

            // Skip exports whose target file no longer exists on disk and is not
            // tracked as a current generated file (it may not have been written
            // this run because the content was unchanged).
            if (!ExportTargetExistsOnDisk(directory, fileName) && !generatedFiles.ContainsKey(Path.GetFullPath(Path.Combine(directory, $"{fileName}.ts"))))
            {
                continue;
            }

            finalExports.Add(export);
        }

        // Insert each new export individually at its best-effort alphabetical position
        foreach (var newFileName in newExportsToAdd)
        {
            var newExport = $"./{newFileName}";
            var insertIndex = finalExports.Count; // Default to end

            // Find the best position: before the first export that's alphabetically greater
            for (var i = 0; i < finalExports.Count; i++)
            {
                var existingFileName = finalExports[i].TrimStart('.', '/');
                if (string.Compare(newFileName, existingFileName, StringComparison.OrdinalIgnoreCase) < 0)
                {
                    insertIndex = i;
                    break;
                }
            }

            finalExports.Insert(insertIndex, newExport);
        }

        // Check if anything changed (compare unsorted since we preserve order)
        if (existingExports.Count == finalExports.Count &&
            existingExports.SequenceEqual(finalExports))
        {
            // No changes - don't rewrite
            return false;
        }

        // Build the final content
        var contentLines = new List<string>();

        // Add manual lines first (comments, imports, etc.)
        if (manualLines.Count > 0)
        {
            contentLines.AddRange(manualLines);
        }

        // Add export statements
        foreach (var export in finalExports)
        {
            contentLines.Add($"export * from '{export}';");
        }

        var content = string.Join(Environment.NewLine, contentLines);
        if (!string.IsNullOrEmpty(content))
        {
            content += Environment.NewLine;
        }

        // If the file exists, compare a normalized version (trim and ignore empty lines)
        if (File.Exists(indexPath))
        {
            var existing = File.ReadAllText(indexPath);
            static string Normalize(string s) => string.Join('\n', s.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries).Select(l => l.Trim()));
            if (Normalize(existing) == Normalize(content))
            {
                // Equivalent content (ignoring blank lines/trim) — don't rewrite
                return false;
            }
        }

        File.WriteAllText(indexPath, content);
        var relPath = GetRelativePath(outputPath, indexPath);
        message($"    Updated index: {relPath}");
        return true;
    }

    /// <summary>
    /// Updates all index.ts files in directories that have generated content, and also
    /// scans for existing index files under the output path that may have stale exports
    /// pointing to files that no longer exist on disk.
    /// </summary>
    /// <param name="directories">Collection of directories with generated content.</param>
    /// <param name="generatedFiles">Collection of all generated file paths.</param>
    /// <param name="orphanedFiles">Collection of orphaned file paths that were deleted.</param>
    /// <param name="message">Logger to use for outputting messages.</param>
    /// <param name="outputPath">The base output path.</param>
    /// <returns>A tuple containing (WrittenCount, SkippedCount).</returns>
    public static (int WrittenCount, int SkippedCount) UpdateAllIndexFiles(IEnumerable<string> directories, IDictionary<string, GeneratedFileMetadata> generatedFiles, IEnumerable<string> orphanedFiles, Action<string> message, string outputPath)
    {
        var writtenCount = 0;
        var skippedCount = 0;

        // Combine explicitly tracked directories with any directory under outputPath
        // that has an existing index.ts file, to catch stale exports from previous runs.
        var allDirectories = new HashSet<string>(directories, StringComparer.Ordinal);

        if (Directory.Exists(outputPath))
        {
            foreach (var indexFile in Directory.GetFiles(outputPath, "index.ts", SearchOption.AllDirectories))
            {
                var dir = Path.GetDirectoryName(indexFile);
                if (dir is not null)
                {
                    allDirectories.Add(dir);
                }
            }
        }

        foreach (var directory in allDirectories)
        {
            var wasWritten = UpdateIndexFile(directory, generatedFiles, orphanedFiles, message, outputPath);
            if (wasWritten)
            {
                writtenCount++;
            }
            else
            {
                skippedCount++;
            }
        }

        return (writtenCount, skippedCount);
    }

    /// <summary>
    /// Checks whether an existing index.ts has at least one export whose target file
    /// exists on disk but is not a proxy-generated file (e.g. hand-written .tsx components).
    /// </summary>
    /// <param name="indexPath">The path to the index.ts file to inspect.</param>
    /// <param name="directory">The directory containing the index.ts file.</param>
    static bool HasLiveNonGeneratedExports(string indexPath, string directory)
    {
        foreach (var line in File.ReadAllLines(indexPath))
        {
            var match = ExportRegex().Match(line);
            if (!match.Success)
            {
                continue;
            }

            // Check common TypeScript extensions for the export target
            foreach (var ext in (string[])[".ts", ".tsx"])
            {
                var filePath = Path.Combine(directory, $"{match.Groups["path"].Value.TrimStart('.', '/')}{ext}");
                if (!File.Exists(filePath))
                {
                    continue;
                }

                // If the file is not proxy-generated, this is a live non-generated export
                if (!GeneratedFileMetadata.IsGeneratedFile(filePath, out _))
                {
                    return true;
                }
            }
        }

        return false;
    }

    static bool ExportTargetExistsOnDisk(string directory, string fileName)
    {
        foreach (var ext in (string[])[".ts", ".tsx"])
        {
            if (File.Exists(Path.Combine(directory, $"{fileName}{ext}")))
            {
                return true;
            }
        }

        return false;
    }

    [GeneratedRegex(@"^\s*export\s+\*\s+from\s+['""](?<path>.+)['""]\s*;?\s*$", RegexOptions.ExplicitCapture, 1000)]
    private static partial Regex ExportRegex();

    static string GetRelativePath(string basePath, string fullPath)
    {
        if (fullPath.StartsWith(basePath, StringComparison.OrdinalIgnoreCase))
        {
            var relative = fullPath[basePath.Length..].TrimStart(Path.DirectorySeparatorChar);
            return relative.Replace(Path.DirectorySeparatorChar, '/');
        }

        return fullPath;
    }
}
