// @generated by Cratis. Source: AspNetCore.Features.Reservations.ReserveTable. Time: 2026-07-29T10:05:48.0249040Z. Hash: F0ECF86F48875E1D35BC7F6FD546E16E772ABB5BDF502CCDD9D81BD5E0794C83
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IReserveTable {
    concurrency?: number;
    description?: string;
    guest?: string;
    reference?: string;
}


export class ReserveTable extends Command<IReserveTable> implements IReserveTable {
    readonly route: string = '/api/features/reservations';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('concurrency', Number, false),
        new PropertyDescriptor('description', String, false),
        new PropertyDescriptor('guest', String, false),
        new PropertyDescriptor('reference', String, false),
    ];

    private _concurrency!: number;
    private _description!: string;
    private _guest!: string;
    private _reference!: string;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get concurrency(): number {
        return this._concurrency;
    }

    set concurrency(value: number) {
        this._concurrency = value;
        this.propertyChanged('concurrency');
    }
    get description(): string {
        return this._description;
    }

    set description(value: string) {
        this._description = value;
        this.propertyChanged('description');
    }
    get guest(): string {
        return this._guest;
    }

    set guest(value: string) {
        this._guest = value;
        this.propertyChanged('guest');
    }
    get reference(): string {
        return this._reference;
    }

    set reference(value: string) {
        this._reference = value;
        this.propertyChanged('reference');
    }

    static use(initialValues?: IReserveTable): [ReserveTable, SetCommandValues<IReserveTable>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<ReserveTable, IReserveTable>(ReserveTable, initialValues);
    }
}
