<?xml version="1.0" encoding="UTF-8" ?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Cratis.Arc.Chronicle</AssemblyName>
        <RootNamespace>Cratis.Arc.Chronicle</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Cratis.Arc.Chronicle.Specs" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../Arc.Core/Arc.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="System.Collections.Immutable" />
        <PackageReference Include="Cratis.Chronicle" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Chronicle.CodeAnalysis/Chronicle.CodeAnalysis.csproj" 
                          OutputItemType="Analyzer" 
                          ReferenceOutputAssembly="false" />
        <ProjectReference Include="../Chronicle.CodeAnalysis.CodeFixes/Chronicle.CodeAnalysis.CodeFixes.csproj"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all" />
    </ItemGroup>
    <ItemGroup>
        <None Include="../Chronicle.CodeAnalysis/bin/$(Configuration)/netstandard2.0/Cratis.Arc.Chronicle.CodeAnalysis.dll"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Visible="false" />
        <None Include="../Chronicle.CodeAnalysis.CodeFixes/bin/$(Configuration)/netstandard2.0/Cratis.Arc.Chronicle.CodeAnalysis.CodeFixes.dll"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Visible="false" />
    </ItemGroup>
</Project>