// @generated by Cratis. Source: Cratis.Arc.Queries.QueryHealth. Time: 2026-06-10T13:06:47.1076820Z. Hash: 66CEB9C71C32D3D257721DEEBEE002263FB75878B9D350FB7C802C4563D7A0BF
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { QueryHealth } from './QueryHealth';


/**
 * Observes query health as a real-time stream.
 */
export class ObserveHealth extends ObservableQueryFor<QueryHealth> {
    readonly route: string = '/.cratis/queries/health';
    readonly queryName: string = 'Cratis.Arc.Queries.QueryHealth.ObserveHealth';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: QueryHealth = {} as any;

    constructor() {
        super(QueryHealth, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<QueryHealth>] {
        const [result] = useObservableQuery<QueryHealth, ObserveHealth>(ObserveHealth);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<QueryHealth>] {
        const [result] = useSuspenseObservableQuery<QueryHealth, ObserveHealth>(ObserveHealth);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<ObserveHealth, QueryHealth> {
        return new ObservableQueryWhen<ObserveHealth, QueryHealth>(ObserveHealth, condition);
    }
}
