// @generated by Cratis. Source: Cratis.Arc.Queries.QuerySubscriber. Time: 2026-09-02T19:07:21.6351200Z. Hash: D6D170B5391D311236427F38A9E9CB78DB643B8CFEA08C7AD89A4102CF5D3D59
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { QuerySubscriptionClientInfo } from './QuerySubscriptionClientInfo';

/**
 * Represents a single active subscriber for a query, combining connection and subscription data.
 */
export class QuerySubscriber {

    /**
     * Gets the connection identifier (e.g. `ws-1` for WebSocket, a GUID for SSE).
     */
    @field(String)
    connectionId!: string;

    /**
     * Gets the transport protocol (`WebSocket` or `SSE`).
     */
    @field(String)
    protocol!: string;

    /**
     * Gets the subscription identifier — the client-generated query ID.
     */
    @field(String)
    subscriptionId!: string;

    /**
     * Gets when this subscription was first established.
     */
    @field(Date)
    connectedAt!: Date;

    /**
     * Gets the last time a ping was sent to this subscriber.
     */
    @field(Date)
    lastPingSentAt?: Date;

    /**
     * Gets the last time a pong was received from this subscriber.
     */
    @field(Date)
    lastPongReceivedAt?: Date;

    /**
     * Gets the last time data was served to this subscriber.
     */
    @field(Date)
    lastDataServedAt?: Date;

    /**
     * Gets client identity and transport information for this subscriber.
     */
    @field(QuerySubscriptionClientInfo)
    clientInfo!: QuerySubscriptionClientInfo;
}
