// @generated by Cratis. Source: Cratis.Arc.Queries.QuerySubscriber. Time: 2026-08-04T06:39:14.9993810Z. Hash: 0CF215ECAB264917403137EBB0CCBF8D2D3B81B29A5DAE954585E536D4D4BFD1
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { QuerySubscriptionClientInfo } from './QuerySubscriptionClientInfo';

/**
 * Represents a single active subscriber for a query, combining connection and subscription data.
 */
export class QuerySubscriber {

    /**
     * Gets the connection identifier (e.g. `ws-1` for WebSocket, a GUID for SSE).
     */
    @field(String)
    connectionId!: string;

    /**
     * Gets the transport protocol (`WebSocket` or `SSE`).
     */
    @field(String)
    protocol!: string;

    /**
     * Gets the subscription identifier &#8212; the client-generated query ID.
     */
    @field(String)
    subscriptionId!: string;

    /**
     * Gets when this subscription was first established.
     */
    @field(Date)
    connectedAt!: Date;

    /**
     * Gets the last time a ping was sent to this subscriber.
     */
    @field(Date)
    lastPingSentAt?: Date;

    /**
     * Gets the last time a pong was received from this subscriber.
     */
    @field(Date)
    lastPongReceivedAt?: Date;

    /**
     * Gets the last time data was served to this subscriber.
     */
    @field(Date)
    lastDataServedAt?: Date;

    /**
     * Gets client identity and transport information for this subscriber.
     */
    @field(QuerySubscriptionClientInfo)
    clientInfo!: QuerySubscriptionClientInfo;
}
