// @generated by Cratis. Source: Cratis.Arc.Queries.QuerySubscriptionAggregate. Time: 2026-06-10T17:24:04.4240450Z. Hash: 4AF219A77F8A5771090D454D6187C03FA8A223668D2D328086BC03ECE833DA07
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { QuerySubscriber } from './QuerySubscriber';

/**
 * Represents a query-centric view of all active subscriptions for a single query.
 */
export class QuerySubscriptionAggregate {

    /**
     * Gets the fully qualified query name (e.g. MyApp.Authors.Listing.AllAuthors).
            Matches the queryName property on the generated TypeScript proxy.
     */
    @field(String)
    queryName!: string;

    /**
     * Gets the total number of active subscribers for this query.
     */
    @field(Number)
    totalSubscriptions!: number;

    /**
     * Gets all active subscribers for this query, one entry per physical connection/subscription pair.
     */
    @field(QuerySubscriber, true)
    subscribers!: QuerySubscriber[];
}
