// @generated by Cratis. Source: TestApps.Features.ObservableCollectionWithGuid.RemoveObservableCollectionWithGuidItem. Time: 2026-04-28T10:58:50.4409900Z. Hash: E0812CD73017A06683F04B28DE2A270A9992675C09D1445D0AAFC6A24ED0E76D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface IRemoveObservableCollectionWithGuidItem {
    id?: Guid;
}

export class RemoveObservableCollectionWithGuidItemValidator extends CommandValidator<IRemoveObservableCollectionWithGuidItem> {
    constructor() {
        super();
    }
}

export class RemoveObservableCollectionWithGuidItem extends Command<IRemoveObservableCollectionWithGuidItem> implements IRemoveObservableCollectionWithGuidItem {
    readonly route: string = '/api/features/observable-collection-with-guid/remove-observable-collection-with-guid-item';
    readonly validation: CommandValidator = new RemoveObservableCollectionWithGuidItemValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Guid, false),
    ];

    private _id!: Guid;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): Guid {
        return this._id;
    }

    set id(value: Guid) {
        this._id = value;
        this.propertyChanged('id');
    }

    static use(initialValues?: IRemoveObservableCollectionWithGuidItem): [RemoveObservableCollectionWithGuidItem, SetCommandValues<IRemoveObservableCollectionWithGuidItem>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RemoveObservableCollectionWithGuidItem, IRemoveObservableCollectionWithGuidItem>(RemoveObservableCollectionWithGuidItem, initialValues);
    }
}
