// @generated by Cratis. Source: Samples.Features.AuthenticationQueries.AuthenticationQueryItem. Time: 2026-10-01T10:15:47.5033350Z. Hash: 752962994E614D898C69415FDE880A9C0D2C9B0D30384D8CD0A4FC71B0637653
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { AuthenticationQueryItem } from './AuthenticationQueryItem';



export class Authenticated extends ObservableQueryFor<AuthenticationQueryItem> {
    readonly route: string = '/api/features/authentication-queries/authenticated';
    readonly queryName: string = 'Samples.Features.AuthenticationQueries.AuthenticationQueryItem.Authenticated';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: AuthenticationQueryItem = {} as AuthenticationQueryItem;

    constructor() {
        super(AuthenticationQueryItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useObservableQuery<AuthenticationQueryItem, Authenticated>(Authenticated);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useSuspenseObservableQuery<AuthenticationQueryItem, Authenticated>(Authenticated);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Authenticated, AuthenticationQueryItem> {
        return new ObservableQueryWhen<Authenticated, AuthenticationQueryItem>(Authenticated, condition);
    }
}
