// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.AuthenticationQueries.AuthenticationQueryItem. Time: 2026-10-03T11:15:01.4419310Z. Hash: 7A25EC5F3E70A51BF30C50D73D4F0493A11A4117BA2E624C8A047002C8EB7F42
// **DO NOT EDIT** - This file is an automatically generated file.
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { ObservableQueryWhen, useObservableQuery, useSuspenseObservableQuery } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { AuthenticationQueryItem } from './AuthenticationQueryItem';



export class Authenticated extends ObservableQueryFor<AuthenticationQueryItem> {
    readonly route: string = '/api/features/authentication-queries/authenticated';
    readonly queryName: string = 'Samples.Features.AuthenticationQueries.AuthenticationQueryItem.Authenticated';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: AuthenticationQueryItem = {} as AuthenticationQueryItem;

    constructor() {
        super(AuthenticationQueryItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useObservableQuery<AuthenticationQueryItem, Authenticated>(Authenticated);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<AuthenticationQueryItem>] {
        const [result] = useSuspenseObservableQuery<AuthenticationQueryItem, Authenticated>(Authenticated);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Authenticated, AuthenticationQueryItem> {
        return new ObservableQueryWhen<Authenticated, AuthenticationQueryItem>(Authenticated, condition);
    }
}
