// @generated by Cratis. Source: Cratis.Arc.Queries.QueryHealth. Time: 2026-07-20T10:41:43.4511480Z. Hash: 10FA08752A67EB94790A87B56305D841EB967B0E5D31CF0F32400EE7A7A34A3B
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { QueryHealth } from './QueryHealth';



/**
 * Observes query health as a real-time stream.
 */
export class ObserveHealth extends ObservableQueryFor<QueryHealth> {
    readonly route: string = '/.cratis/queries/health';
    readonly queryName: string = 'Cratis.Arc.Queries.QueryHealth.ObserveHealth';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: QueryHealth = {} as any;

    constructor() {
        super(QueryHealth, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<QueryHealth>] {
        const [result] = useObservableQuery<QueryHealth, ObserveHealth>(ObserveHealth);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<QueryHealth>] {
        const [result] = useSuspenseObservableQuery<QueryHealth, ObserveHealth>(ObserveHealth);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<ObserveHealth, QueryHealth> {
        return new ObservableQueryWhen<ObserveHealth, QueryHealth>(ObserveHealth, condition);
    }
}
