// @generated by Cratis. Source: Cratis.Arc.Queries.QueryHealth. Time: 2026-06-10T13:06:48.3603960Z. Hash: 9D12B2B26F81B636CC9F5FD874986ADF07B9EF23453679304BE2F112459F9ABF
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { QueryConnectionHealth } from './QueryConnectionHealth';

/**
 * Read model for query health monitoring.
 */
export class QueryHealth {

    /**
     * Gets the connection health information.
     */
    @field(QueryConnectionHealth, true)
    connections!: QueryConnectionHealth[];

    /**
     * Gets the total number of active connections.
     */
    @field(Number)
    totalConnections!: number;

    /**
     * Gets the total number of active subscriptions across all connections.
     */
    @field(Number)
    totalSubscriptions!: number;
}
