// @generated by Cratis. Source: Cratis.Arc.Queries.QuerySubscriptionAggregate. Time: 2026-08-29T06:40:16.4772910Z. Hash: 778A7A92E85B2D2F6186B90E7243E1D0742E4FC3F8BF3DE5FA8DD17FF42F778D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { QuerySubscriber } from './QuerySubscriber';

/**
 * Represents a query-centric view of all active subscriptions for a single query.
 */
export class QuerySubscriptionAggregate {

    /**
     * Gets the fully qualified query name (e.g. &#x60;MyApp.Authors.Listing.AllAuthors&#x60;). Matches the &#x60;queryName&#x60; property on the generated TypeScript proxy.
     */
    @field(String)
    queryName!: string;

    /**
     * Gets the total number of active subscribers for this query.
     */
    @field(Number)
    totalSubscriptions!: number;

    /**
     * Gets all active subscribers for this query, one entry per physical connection/subscription pair.
     */
    @field(QuerySubscriber, true)
    subscribers!: QuerySubscriber[];
}
