// @generated by Cratis. Source: Cratis.Arc.Queries.QueryHealth. Time: 2026-06-10T17:24:08.8041280Z. Hash: E8454200D26C2AA60E6D459E171DFBE70BBF2B6A9B990DD54601830E7B03371B
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { QueryConnectionHealth } from './QueryConnectionHealth';
import { QuerySubscriptionAggregate } from './QuerySubscriptionAggregate';

/**
 * Read model for query health monitoring.
 */
export class QueryHealth {

    /**
     * Gets the connection health information.
     */
    @field(QueryConnectionHealth, true)
    connections!: QueryConnectionHealth[];

    /**
     * Gets the total number of active connections.
     */
    @field(Number)
    totalConnections!: number;

    /**
     * Gets the total number of active subscriptions across all connections.
     */
    @field(Number)
    totalSubscriptions!: number;

    /**
     * Gets a query-centric view of all active subscriptions, grouped by query name.
     */
    @field(QuerySubscriptionAggregate, true)
    querySubscriptions!: QuerySubscriptionAggregate[];
}
