// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.QueryShowcase.ShowcaseItem, Samples.Features.QueryShowcase.ShowcaseItem, Samples.Features.QueryShowcase.ShowcaseItem, Samples.Features.QueryShowcase.ShowcaseItem, Samples.Features.QueryShowcase.ShowcaseItem. Time: 2026-10-03T11:14:56.9415300Z. Hash: EF03F1F5CE6EB5069A0C70B390FB0EDDA53E8FA943C6EAAFDA4653B6722023A4
// **DO NOT EDIT** - This file is an automatically generated file.
import { ChangeSet, ObservableQueryFor, Paging, QueryFor, QueryResultWithState, Sorting } from '@cratis/arc/queries';
import { ObservableQueryWhen, PerformQuery, QueryWhen, SetPage, SetPageSize, SetSorting, useChangeStream, useObservableQuery, useObservableQueryWithPaging, useQuery, useQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useSuspenseQuery, useSuspenseQueryWithPaging } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

export interface ByIdParameters {
    id: number;
}


export class ById extends QueryFor<ShowcaseItem, ByIdParameters> {
    readonly route: string = '/api/features/query-showcase/by-id';
    readonly queryName: string = 'Samples.Features.QueryShowcase.ShowcaseItem.ById';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem = {} as ShowcaseItem;

    constructor() {
        super(ShowcaseItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', Number, false),
    ];

    id!: number;


    static use(args?: ByIdParameters): [QueryResultWithState<ShowcaseItem>, PerformQuery<ByIdParameters>, SetSorting] {
        return useQuery<ShowcaseItem, ById, ByIdParameters>(ById, args);
    }

    static useSuspense(args?: ByIdParameters): [QueryResultWithState<ShowcaseItem>, PerformQuery<ByIdParameters>, SetSorting] {
        return useSuspenseQuery<ShowcaseItem, ById, ByIdParameters>(ById, args);
    }

    static when(condition: boolean): QueryWhen<ById, ShowcaseItem, ByIdParameters> {
        return new QueryWhen<ById, ShowcaseItem, ByIdParameters>(ById, condition);
    }
}

class GetAllSortBy {

    constructor(readonly query: GetAll) {
    }

}

class GetAllSortByWithoutQuery {

}


export class GetAll extends QueryFor<ShowcaseItem[]> {
    readonly route: string = '/api/features/query-showcase/get-all';
    readonly queryName: string = 'Samples.Features.QueryShowcase.ShowcaseItem.GetAll';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem[] = [];
    private readonly _sortBy: GetAllSortBy;
    private static readonly _sortBy: GetAllSortByWithoutQuery = new GetAllSortByWithoutQuery();

    constructor() {
        super(ShowcaseItem, true);
        this._sortBy = new GetAllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): GetAllSortBy {
        return this._sortBy;
    }

    static get sortBy(): GetAllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, PerformQuery, SetSorting] {
        return useQuery<ShowcaseItem[], GetAll>(GetAll, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<ShowcaseItem[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, PerformQuery, SetSorting] {
        return useSuspenseQuery<ShowcaseItem[], GetAll>(GetAll, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<ShowcaseItem[], GetAll>(GetAll, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): QueryWhen<GetAll, ShowcaseItem[]> {
        return new QueryWhen<GetAll, ShowcaseItem[]>(GetAll, condition);
    }
}

export class Latest extends ObservableQueryFor<ShowcaseItem> {
    readonly route: string = '/api/features/query-showcase/latest';
    readonly queryName: string = 'Samples.Features.QueryShowcase.ShowcaseItem.Latest';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem = {} as ShowcaseItem;

    constructor() {
        super(ShowcaseItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<ShowcaseItem>] {
        const [result] = useObservableQuery<ShowcaseItem, Latest>(Latest);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<ShowcaseItem>] {
        const [result] = useSuspenseObservableQuery<ShowcaseItem, Latest>(Latest);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Latest, ShowcaseItem> {
        return new ObservableQueryWhen<Latest, ShowcaseItem>(Latest, condition);
    }
}

class AllSortBy {

    constructor(readonly query: All) {
    }

}

class AllSortByWithoutQuery {

}


export class All extends ObservableQueryFor<ShowcaseItem[]> {
    readonly route: string = '/api/features/query-showcase/all';
    readonly queryName: string = 'Samples.Features.QueryShowcase.ShowcaseItem.All';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShowcaseItem[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(ShowcaseItem, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting] {
        return useObservableQuery<ShowcaseItem[], All>(All, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<ShowcaseItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting] {
        return useSuspenseObservableQuery<ShowcaseItem[], All>(All, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<ShowcaseItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<ShowcaseItem[], All>(All, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: ShowcaseItem) => unknown, sorting?: Sorting): ChangeSet<ShowcaseItem> {
        return useChangeStream<ShowcaseItem, All>(All, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<All, ShowcaseItem[]> {
        return new ObservableQueryWhen<All, ShowcaseItem[]>(All, condition);
    }
}

export class ShowcaseItem {
    @field(Number)
    id!: number;
    @field(String)
    name!: string;
    @field(Date)
    updatedAt!: Date;
}
