// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus. Time: 2026-10-03T11:15:01.4419310Z. Hash: 914DADB221970242B483D3F540C15FF8BBB3D4350D9F4A2259AF1B5CA55067DF
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';

export class CrossCuttingAuthorizationStatus {
    @field(String)
    message!: string;
    @field(Date)
    checkedAt!: Date;
}
