// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.CrossCuttingAuthorization.RunSecuredCommand. Time: 2026-10-09T19:44:56.2751420Z. Hash: 467B3368F5E73601BCED0DD240339B8A00BAA071A5F3DDD778DF2E86BE0B086A
// **DO NOT EDIT** - This file is an automatically generated file.
import { Command } from '@cratis/arc/commands';
import { ClearCommandValues, SetCommandValues, useCommand } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';

export interface IRunSecuredCommand {
    message?: string;
}


export class RunSecuredCommand extends Command<IRunSecuredCommand, string> implements IRunSecuredCommand {
    readonly route: string = '/api/features/cross-cutting-authorization';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('message', String, false),
    ];

    #message!: string;

    constructor() {
        super(String, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get message(): string {
        return this.#message;
    }

    set message(value: string) {
        this.#message = value;
        this.propertyChanged('message');
    }

    static use(initialValues?: IRunSecuredCommand): [RunSecuredCommand, SetCommandValues<IRunSecuredCommand>, ClearCommandValues] {
        return useCommand<RunSecuredCommand, IRunSecuredCommand, string>(RunSecuredCommand, initialValues);
    }
}
