// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus. Time: 2026-10-03T11:15:01.4419310Z. Hash: 019931DA973C5B6C7FF8D9433C01113785291B62B843376C0038803002D1CBBF
// **DO NOT EDIT** - This file is an automatically generated file.
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { PerformQuery, QueryWhen, SetSorting, useQuery, useSuspenseQuery } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { CrossCuttingAuthorizationStatus } from './CrossCuttingAuthorizationStatus';



export class Secured extends QueryFor<CrossCuttingAuthorizationStatus> {
    readonly route: string = '/api/features/cross-cutting-authorization/secured';
    readonly queryName: string = 'Samples.Features.CrossCuttingAuthorization.CrossCuttingAuthorizationStatus.Secured';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: CrossCuttingAuthorizationStatus = {} as CrossCuttingAuthorizationStatus;

    constructor() {
        super(CrossCuttingAuthorizationStatus, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<CrossCuttingAuthorizationStatus>, PerformQuery, SetSorting] {
        return useQuery<CrossCuttingAuthorizationStatus, Secured>(Secured);
    }

    static useSuspense(): [QueryResultWithState<CrossCuttingAuthorizationStatus>, PerformQuery, SetSorting] {
        return useSuspenseQuery<CrossCuttingAuthorizationStatus, Secured>(Secured);
    }

    static when(condition: boolean): QueryWhen<Secured, CrossCuttingAuthorizationStatus> {
        return new QueryWhen<Secured, CrossCuttingAuthorizationStatus>(Secured, condition);
    }
}
