// @generated by Cratis. Source: Samples.Features.Ticker.Ticker. Time: 2026-10-01T10:15:47.5033350Z. Hash: 87A81059F83A8DE2D20DA453E4AF347CCC4A75E09ABCC52B4A336390CEA3A642
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Ticker } from './Ticker';



export class Observe extends ObservableQueryFor<Ticker> {
    readonly route: string = '/api/features/ticker/observe';
    readonly queryName: string = 'Samples.Features.Ticker.Ticker.Observe';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Ticker = {} as Ticker;

    constructor() {
        super(Ticker, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<Ticker>] {
        const [result] = useObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<Ticker>] {
        const [result] = useSuspenseObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Observe, Ticker> {
        return new ObservableQueryWhen<Observe, Ticker>(Observe, condition);
    }
}
