// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.Ticker.Ticker. Time: 2026-10-03T11:15:01.4419310Z. Hash: 0123A845612EB4571D079CBD7EE36B0931DAC2996D125AC20315A765B3A33543
// **DO NOT EDIT** - This file is an automatically generated file.
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { ObservableQueryWhen, useObservableQuery, useSuspenseObservableQuery } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Ticker } from './Ticker';



export class Observe extends ObservableQueryFor<Ticker> {
    readonly route: string = '/api/features/ticker/observe';
    readonly queryName: string = 'Samples.Features.Ticker.Ticker.Observe';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Ticker = {} as Ticker;

    constructor() {
        super(Ticker, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<Ticker>] {
        const [result] = useObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<Ticker>] {
        const [result] = useSuspenseObservableQuery<Ticker, Observe>(Observe);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<Observe, Ticker> {
        return new ObservableQueryWhen<Observe, Ticker>(Observe, condition);
    }
}
