// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Samples.Features.Ticker.Ticker. Time: 2026-10-03T11:15:01.4419310Z. Hash: C4487636AB19BBD3D069BE224C853AE56D601041751097EE0D7B66DF91A51491
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';

export class Ticker {
    @field(Number)
    count!: number;
    @field(Date)
    lastUpdated!: Date;
}
