// @generated by Cratis. Source: Samples.Features.Ticker.Ticker. Time: 2026-10-01T11:06:36.0735590Z. Hash: 355912141C61ECDB7B7F598E90EA18883AD0EB2B75F20666AED499CCB8A0C084
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

export class Ticker {
    @field(Number)
    count!: number;
    @field(Date)
    lastUpdated!: Date;
}
