// @generated by Cratis. Source: TestApps.Features.LiveFeed.LiveFeed. Time: 2026-03-26T10:40:07.6866700Z. Hash: CC337BA587D27434CA2C42F46982398DE3D7704FFCA9E923EBCCD3BCDE796D8D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, SortingActions, SortingActionsForObservableQuery, Paging } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { LiveFeed } from './LiveFeed';

class ByAuthorSortBy {
    private _author: SortingActionsForObservableQuery<LiveFeed[]>;

    constructor(readonly query: ByAuthor) {
        this._author = new SortingActionsForObservableQuery<LiveFeed[]>('author', query);
    }

    get author(): SortingActionsForObservableQuery<LiveFeed[]> {
        return this._author;
    }
}

class ByAuthorSortByWithoutQuery {
    private _author: SortingActions  = new SortingActions('author');

    get author(): SortingActions {
        return this._author;
    }
}

export interface ByAuthorParameters {
    
    author: string;
}
export class ByAuthor extends ObservableQueryFor<LiveFeed[], ByAuthorParameters> {
    readonly route: string = '/api/features/live-feed/by-author';
    readonly queryName: string = 'TestApps.Features.LiveFeed.LiveFeed.ByAuthor';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: LiveFeed[] = [];
    private readonly _sortBy: ByAuthorSortBy;
    private static readonly _sortBy: ByAuthorSortByWithoutQuery = new ByAuthorSortByWithoutQuery();

    constructor() {
        super(LiveFeed, true);
        this._sortBy = new ByAuthorSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
            'author',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('author', String),
    ];

    author!: string;

    get sortBy(): ByAuthorSortBy {
        return this._sortBy;
    }

    static get sortBy(): ByAuthorSortByWithoutQuery {
        return this._sortBy;
    }

    static use(args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useObservableQuery<LiveFeed[], ByAuthor, ByAuthorParameters>(ByAuthor, args, sorting);
    }

    static useWithPaging(pageSize: number, args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<LiveFeed[], ByAuthor>(ByAuthor, new Paging(0, pageSize), args, sorting);
    }

    static useSuspense(args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting] {
        return useSuspenseObservableQuery<LiveFeed[], ByAuthor, ByAuthorParameters>(ByAuthor, args, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, args?: ByAuthorParameters, sorting?: Sorting): [QueryResultWithState<LiveFeed[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<LiveFeed[], ByAuthor>(ByAuthor, new Paging(0, pageSize), args, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<ByAuthor, LiveFeed[], ByAuthorParameters> {
        return new ObservableQueryWhen<ByAuthor, LiveFeed[], ByAuthorParameters>(ByAuthor, condition);
    }
}
