// @generated by Cratis. Source: AspNetCore.Features.LiveFeed.LiveFeedController. Time: 2026-07-20T10:41:43.4511480Z. Hash: 42FE7A6C97A612E27A0DE92B9A9EA3988C687EEC3698AA5C05CDB65ABD923371
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { LiveFeedMessage } from './LiveFeedMessage';

export interface IPost {
    author?: string;
    text?: string;
}


export class Post extends Command<IPost, LiveFeedMessage> implements IPost {
    readonly route: string = '/api/live-feed/post';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('author', String, false),
        new PropertyDescriptor('text', String, false),
    ];

    private _author!: string;
    private _text!: string;

    constructor() {
        super(LiveFeedMessage, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get author(): string {
        return this._author;
    }

    set author(value: string) {
        this._author = value;
        this.propertyChanged('author');
    }
    get text(): string {
        return this._text;
    }

    set text(value: string) {
        this._text = value;
        this.propertyChanged('text');
    }

    static use(initialValues?: IPost): [Post, SetCommandValues<IPost>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<Post, IPost>(Post, initialValues);
    }
}
