// @generated by Cratis. Source: AspNetCore.Features.LiveFeed.LiveFeedMessage. Time: 2026-03-23T07:05:31.7740895Z. Hash: 0319AC2BBE96169357020137A4FE88819D4E0F8A1F36FB4550AA4F319E099E77
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

export class LiveFeedMessage {
    @field(String)
    author!: string;
    @field(String)
    text!: string;
    @field(Date)
    postedAt!: Date;
}
