// @generated by Cratis. Source: TestApps.Features.LiveFeed.LiveFeed. Time: 2026-03-26T10:40:07.6866700Z. Hash: 645AEAB42160FC7CA75732ED091E18EE3D115B089EDFED15D9CE324A7F5DEDAA
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

export class LiveFeed {
    @field(String)
    author!: string;
    @field(String)
    text!: string;
    @field(Date)
    postedAt!: Date;
}
